// model.json -> Java sources. Every emitter here is a pure function of the model.
//
// Ownership rule:
//   * `overwrite: true`  -> generator-owned. Always rewritten. NEVER hand-edit.
//   * `once: true`       -> scaffolded once if absent, then owned by TDD. Contains
//                           the UnsupportedOperationException stubs for [bracketed]
//                           fields, i.e. the only places where business decisions live.

import { runtimeFiles } from './runtime.js';

const HEADER = (source) =>
  `// GENERATED by the backend codegen from ${source} — DO NOT EDIT.\n` +
  `// Change the event model and regenerate; edits here are overwritten.\n`;

const ONCE_HEADER = (what) =>
  `// SCAFFOLDED ONCE by scripts/codegen — this file is YOURS.\n` +
  `// It holds the business decisions for ${what} ([bracketed] model fields).\n` +
  `// Replace each UnsupportedOperationException by driving it from a GWT scenario (TDD).\n`;

const uniq = (xs) => [...new Set(xs)].filter(Boolean);
const importBlock = (imports) =>
  uniq(imports).sort().map((i) => `import ${i};`).join('\n');

const components = (fields) => fields.map((f) => `${f.javaType} ${f.name}`).join(', ');

// --- expression resolution for a target field --------------------------------
// This is where the [bracket] convention pays off: everything derivable is derived,
// everything decided is delegated to the once-scaffolded decider and throws until
// a GWT scenario forces it into existence.
function resolveArg(field, { sourceFields, sourceExpr, deciderVar, deciderArgs = '', fallback }) {
  if (field.convention) return { expr: field.conventionExpr, imports: field.imports };
  if (field.bracketed) {
    return { expr: `${deciderVar}.${field.name}(${deciderArgs})`, imports: [], decided: true };
  }
  const match = sourceFields.find((f) => f.name === field.name);
  if (match) return { expr: `${sourceExpr}.${field.name}()`, imports: [] };
  if (fallback) return { expr: fallback(field), imports: [] };
  return null;
}

// --- emitters ----------------------------------------------------------------

function valueObject(vo) {
  const needsList = vo.fields.some((f) => f.javaType.startsWith('List<'));
  return {
    package: vo.package,
    className: vo.className,
    overwrite: true,
    content: `${HEADER('business-definitions-raw.md')}package ${vo.package};

${needsList ? 'import java.util.List;\n\n' : ''}public record ${vo.className}(${components(vo.fields)}) {
}
`,
  };
}

function event(e, base) {
  const imports = importBlock([
    'java.util.UUID',
    'lombok.Builder',
    `${base}.eventstream.DomainEvent`,
    ...e.fields.flatMap((f) => f.imports),
  ]);
  return {
    package: e.package,
    className: e.className,
    overwrite: true,
    content: `${HEADER('events.md')}package ${e.package};

${imports}

@Builder
public record ${e.className}(UUID aggregateId, ${components(e.fields)}) implements DomainEvent {
    @Override
    public DomainEventType eventType() {
        return DomainEventType.${e.typeEnum};
    }
}
`,
  };
}

function eventType(events, base) {
  const constants = events.map((e) => `    ${e.typeEnum},`).join('\n');
  return {
    package: `${base}.domain.events`,
    className: 'DomainEventType',
    overwrite: true,
    content: `${HEADER('events.md')}package ${base}.domain.events;

public enum DomainEventType {
${constants}
}
`,
  };
}

function command(c) {
  const imports = importBlock(['lombok.Builder', ...c.fields.flatMap((f) => f.imports)]);
  return {
    package: c.package,
    className: c.className,
    overwrite: true,
    content: `${HEADER('commands.md')}package ${c.package};

${imports}

@Builder
public record ${c.className}(${components(c.fields)}) {
}
`,
  };
}

function commandHandler(c, e, base) {
  const args = [];
  const extraImports = [];
  let needsDecider = false;

  for (const f of e.fields) {
    const r = resolveArg(f, {
      sourceFields: c.fields,
      sourceExpr: 'command',
      deciderVar: 'decider',
    });
    if (!r) {
      throw new Error(
        `Model gap: event "${e.id}" field "${f.label}" is not supplied by command "${c.id}" ` +
          `and is not [bracketed]. Either add it to the command or bracket it.`,
      );
    }
    if (r.decided) needsDecider = true;
    extraImports.push(...r.imports);
    args.push(r.expr);
  }

  const deciderField = needsDecider ? `    private final ${c.deciderClassName} decider;\n` : '';
  const deciderParam = needsDecider ? `, ${c.deciderClassName} decider` : '';
  const deciderAssign = needsDecider ? `\n        this.decider = decider;` : '';

  const imports = importBlock([
    'java.util.List',
    'java.util.UUID',
    'org.springframework.stereotype.Component',
    'org.springframework.transaction.annotation.Transactional',
    'org.springframework.web.bind.annotation.PostMapping',
    'org.springframework.web.bind.annotation.RequestBody',
    'org.springframework.web.bind.annotation.RestController',
    `${base}.eventstream.CommandHandler`,
    `${base}.eventstream.EventStream`,
    `${e.package}.${e.className}`,
    ...extraImports,
  ]);

  const argList = args.map((a) => `                ${a}`).join(',\n');

  return {
    package: c.package,
    className: c.handlerClassName,
    overwrite: true,
    content: `${HEADER('commands.md + events.md')}package ${c.package};

${imports}

@RestController
@Component
@Transactional
public class ${c.handlerClassName} implements CommandHandler<${c.className}> {

    private final EventStream eventStream;
${deciderField}
    public ${c.handlerClassName}(EventStream eventStream${deciderParam}) {
        this.eventStream = eventStream;${deciderAssign}
    }

    @PostMapping("${c.postMapping}")
    @Override
    public UUID handle(@RequestBody ${c.className} command) {
        var aggregateId = UUID.randomUUID();
        eventStream.append(List.of(new ${e.className}(
                aggregateId,
${argList})));
        return aggregateId;
    }
}
`,
    needsDecider,
  };
}

function commandDecider(c, e) {
  const decided = e.fields.filter((f) => f.bracketed && !f.convention);
  const methods = decided
    .map(
      (f) => `    public ${f.javaType} ${f.name}() {
        throw new UnsupportedOperationException(
                "[${f.label}] on event '${e.id}' is a business decision with no GWT scenario yet");
    }`,
    )
    .join('\n\n');
  const imports = importBlock([
    'org.springframework.stereotype.Component',
    ...decided.flatMap((f) => f.imports),
  ]);
  return {
    package: c.package,
    className: c.deciderClassName,
    once: true,
    content: `${ONCE_HEADER(`command "${c.id}"`)}package ${c.package};

${imports}

@Component
public class ${c.deciderClassName} {

${methods}
}
`,
  };
}

function readModel(rm) {
  const imports = importBlock(rm.fields.flatMap((f) => f.imports));
  return {
    package: rm.package,
    className: rm.className,
    overwrite: true,
    content: `${HEADER('readmodels.md')}package ${rm.package};

${imports ? imports + '\n\n' : ''}public record ${rm.className}(${components(rm.fields)}) {
}
`,
  };
}

function projector(rm, eventsById, base) {
  if (!rm.onDemand) {
    throw new Error(
      `Read model "${rm.id}" has no <aggregate>:Id line. Persisting projectors are not ` +
        `supported by the generator yet — add the aggregate id or implement it by hand.`,
    );
  }

  const extraImports = [];
  let needsDecider = false;
  const applies = rm.subscribes.map((eid) => {
    const e = eventsById.get(eid);
    const args = rm.fields.map((f) => {
      const r = resolveArg(f, {
        sourceFields: e.fields,
        sourceExpr: 'event',
        deciderVar: 'decider',
        deciderArgs: 'state, event',
        fallback: (field) => `state == null ? null : state.${field.name}()`,
      });
      if (r.decided) needsDecider = true;
      extraImports.push(...r.imports);
      return r.expr;
    });
    extraImports.push(`${e.package}.${e.className}`);
    return `    @Override
    public ${rm.className} apply(${rm.className} state, ${e.className} event) {
        return new ${rm.className}(
${args.map((a) => `                ${a}`).join(',\n')});
    }`;
  });

  const deciderField = needsDecider
    ? `    private final ${rm.deciderClassName} decider;\n`
    : '';
  const deciderParam = needsDecider ? `, ${rm.deciderClassName} decider` : '';
  const deciderAssign = needsDecider ? `\n        this.decider = decider;` : '';

  const imports = importBlock([
    'java.util.UUID',
    'org.springframework.stereotype.Component',
    'org.springframework.web.bind.annotation.GetMapping',
    'org.springframework.web.bind.annotation.PathVariable',
    'org.springframework.web.bind.annotation.RestController',
    `${base}.eventstream.EventStream`,
    `${base}.eventstream.StateProjector`,
    ...extraImports,
  ]);

  return {
    package: rm.package,
    className: rm.projectorClassName,
    overwrite: true,
    needsDecider,
    content: `${HEADER('readmodels.md + events.md')}package ${rm.package};

${imports}

@RestController
@Component
public class ${rm.projectorClassName} implements StateProjector<${rm.className}> {

    private final EventStream eventStream;
${deciderField}
    public ${rm.projectorClassName}(EventStream eventStream${deciderParam}) {
        this.eventStream = eventStream;${deciderAssign}
    }

    @GetMapping("${rm.getMapping}")
    public ${rm.className} ${rm.getterMethod}(@PathVariable UUID aggregateId) {
        return hydrate(null, eventStream.findAllById(aggregateId));
    }

${applies.join('\n\n')}
}
`,
  };
}

function projectionDecider(rm, eventsById) {
  const methods = [];
  const imports = ['org.springframework.stereotype.Component'];
  for (const eid of rm.subscribes) {
    const e = eventsById.get(eid);
    for (const f of rm.fields.filter((x) => x.bracketed && !x.convention)) {
      imports.push(...f.imports, `${e.package}.${e.className}`);
      methods.push(`    public ${f.javaType} ${f.name}(${rm.className} state, ${e.className} event) {
        throw new UnsupportedOperationException(
                "[${f.label}] on read model '${rm.id}' is a projection decision with no GWT scenario yet");
    }`);
    }
  }
  return {
    package: rm.package,
    className: rm.deciderClassName,
    once: true,
    content: `${ONCE_HEADER(`read model "${rm.id}"`)}package ${rm.package};

${importBlock(imports)}

@Component
public class ${rm.deciderClassName} {

${methods.join('\n\n')}
}
`,
  };
}

function stateProjector(events, base) {
  const cases = events
    .map((e) => `            case ${e.typeEnum} -> apply(state, (${e.className}) event);`)
    .join('\n');
  const defaults = events
    .map(
      (e) => `    default S apply(S state, ${e.className} event) {
        return state;
    }`,
    )
    .join('\n\n');
  const imports = importBlock([
    'java.util.Collection',
    ...events.map((e) => `${e.package}.${e.className}`),
  ]);
  return {
    package: `${base}.eventstream`,
    className: 'StateProjector',
    overwrite: true,
    content: `${HEADER('events.md')}package ${base}.eventstream;

${imports}

public interface StateProjector<S> {

    default S hydrate(S state, Collection<DomainEvent> events) {
        return events.stream().reduce(state, this::apply, (_, s2) -> s2);
    }

    private S apply(S state, DomainEvent event) {
        return switch (event.eventType()) {
${cases}
            default -> state;
        };
    }

${defaults}
}
`,
  };
}

function serdeWrapper(e, base) {
  return {
    package: e.serdePackage,
    className: e.serdeClassName,
    overwrite: true,
    content: `${HEADER('events.md')}package ${e.serdePackage};

${importBlock([
  'com.fasterxml.jackson.annotation.JsonTypeName',
  `${base}.domain.events.DomainEventType`,
  `${base}.eventstream.DomainEvent`,
])}

@JsonTypeName("${e.typeEnum}")
public record ${e.serdeClassName}(DomainEvent event) implements DomainEventSerdeWrapper {
    @Override
    public DomainEventType getEventType() {
        return DomainEventType.${e.typeEnum};
    }
}
`,
  };
}

function serdeRegistry(events, base) {
  const subTypes = events
    .map((e) => `        @JsonSubTypes.Type(value = ${e.serdeClassName}.class, name = "${e.typeEnum}"),`)
    .join('\n');
  return {
    package: `${base}.infrastructure`,
    className: 'DomainEventSerdeWrapper',
    overwrite: true,
    content: `${HEADER('events.md')}package ${base}.infrastructure;

${importBlock([
  'com.fasterxml.jackson.annotation.JsonIgnoreProperties',
  'com.fasterxml.jackson.annotation.JsonInclude',
  'com.fasterxml.jackson.annotation.JsonSubTypes',
  'com.fasterxml.jackson.annotation.JsonTypeInfo',
  `${base}.domain.events.DomainEventType`,
  `${base}.eventstream.DomainEvent`,
])}

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "eventType")
@JsonSubTypes({
${subTypes}
})
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public interface DomainEventSerdeWrapper {
    DomainEventType getEventType();
    DomainEvent event();
}
`,
  };
}

function serde(events, base) {
  const cases = events
    .map((e) => `            case ${e.typeEnum} -> new ${e.serdeClassName}(event);`)
    .join('\n');
  return {
    package: `${base}.infrastructure`,
    className: 'DomainEventSerde',
    overwrite: true,
    content: `${HEADER('events.md')}package ${base}.infrastructure;

${importBlock([`${base}.eventstream.DomainEvent`])}

public final class DomainEventSerde {

    private DomainEventSerde() {
    }

    public static DomainEventSerdeWrapper serialize(DomainEvent event) {
        return switch (event.eventType()) {
${cases}
            default -> throw new IllegalArgumentException("No serde wrapper for " + event.eventType());
        };
    }
}
`,
  };
}

// --- test abilities (mechanical DSL, generator-owned) ------------------------

function eventStreamAbility(base) {
  return {
    test: true,
    package: `${base}.eventstream`,
    className: 'EventStreamAbility',
    overwrite: true,
    content: `${HEADER('the event stream infrastructure')}package ${base}.eventstream;

${importBlock([
  `${base}.infrastructure.DomainEventInMemoryRepository`,
  `${base}.infrastructure.EventStreamImpl`,
])}

public interface EventStreamAbility {

    DomainEventInMemoryRepository REPOSITORY = new DomainEventInMemoryRepository();
    EventStream INSTANCE = new EventStreamImpl(REPOSITORY);

    default EventStream getEventStream() {
        return EventStreamAbility.INSTANCE;
    }

    default void reset_event_stream() {
        EventStreamAbility.REPOSITORY.deleteAll();
    }
}
`,
  };
}

function commandAbility(c, base, needsDecider) {
  const deciderArg = needsDecider ? `, new ${c.deciderClassName}()` : '';
  return {
    test: true,
    package: c.package,
    className: c.abilityClassName,
    overwrite: true,
    content: `${HEADER('commands.md')}package ${c.package};

${importBlock([
  'java.util.UUID',
  'java.util.function.Consumer',
  `${base}.eventstream.EventStreamAbility`,
])}

public interface ${c.abilityClassName} extends EventStreamAbility {

    // Qualify when you need the instance itself: ${c.abilityClassName}.INSTANCE
    ${c.handlerClassName} INSTANCE =
            new ${c.handlerClassName}(EventStreamAbility.INSTANCE${deciderArg});

    default ${c.handlerClassName} get${c.handlerClassName}() {
        return ${c.abilityClassName}.INSTANCE;
    }

    /** DSL: ${c.dslMethod} { it.someField("value") } */
    default UUID ${c.dslMethod}(Consumer<${c.className}.${c.className}Builder> testCase) {
        var cmd = ${c.className}.builder();
        testCase.accept(cmd);
        return get${c.handlerClassName}().handle(cmd.build());
    }
}
`,
  };
}

function projectorAbility(rm, base, needsDecider) {
  const deciderArg = needsDecider ? `, new ${rm.deciderClassName}()` : '';
  return {
    test: true,
    package: rm.package,
    className: rm.abilityClassName,
    overwrite: true,
    content: `${HEADER('readmodels.md')}package ${rm.package};

${importBlock([
  'java.util.UUID',
  'java.util.function.Predicate',
  `${base}.eventstream.EventStreamAbility`,
])}

public interface ${rm.abilityClassName} extends EventStreamAbility {

    // Qualify when you need the instance itself: ${rm.abilityClassName}.INSTANCE
    ${rm.projectorClassName} INSTANCE =
            new ${rm.projectorClassName}(EventStreamAbility.INSTANCE${deciderArg});

    default ${rm.projectorClassName} get${rm.projectorClassName}() {
        return ${rm.abilityClassName}.INSTANCE;
    }

    /** DSL: ${rm.dslMethod}(aggregateId) { it.someField() == "value" } */
    default boolean ${rm.dslMethod}(UUID aggregateId, Predicate<${rm.className}> testCase) {
        return testCase.test(get${rm.projectorClassName}().${rm.getterMethod}(aggregateId));
    }
}
`,
  };
}

// --- orchestration -----------------------------------------------------------

export function emit(model) {
  const base = model.meta.basePackage;
  const eventsById = new Map(model.events.map((e) => [e.id, e]));
  const files = [];

  // domain-independent runtime (scaffolded once, then the project's)
  runtimeFiles(base).forEach((f) => files.push(f));

  model.valueObjects.forEach((vo) => files.push(valueObject(vo)));
  model.events.forEach((e) => files.push(event(e, base), serdeWrapper(e, base)));
  files.push(eventType(model.events, base));
  files.push(stateProjector(model.events, base));
  files.push(serdeRegistry(model.events, base));
  files.push(serde(model.events, base));
  files.push(eventStreamAbility(base));

  for (const c of model.commands) {
    const e = eventsById.get(c.producesId);
    const handler = commandHandler(c, e, base);
    files.push(command(c), handler);
    if (handler.needsDecider) files.push(commandDecider(c, e));
    files.push(commandAbility(c, base, handler.needsDecider));
  }

  for (const rm of model.readModels) {
    const p = projector(rm, eventsById, base);
    files.push(readModel(rm), p);
    if (p.needsDecider) files.push(projectionDecider(rm, eventsById));
    files.push(projectorAbility(rm, base, p.needsDecider));
  }

  return files;
}
