// model.json -> Java sources. Every emitter here is a pure function of the model.
//
// Ownership rule:
//   * `overwrite: true, logic: false` -> data/contract files, reconciled add-only.
//   * `overwrite: true, logic: true`  -> logic classes (handlers, projectors,
//                                        repositories, entities): scaffolded once,
//                                        then the project's. Model drift is reported
//                                        as an advisory, never applied over hand edits.
//   * `once: true`                    -> scaffolded once if absent, then owned by TDD.
//                                        Contains the UnsupportedOperationException
//                                        stubs for [bracketed] fields, i.e. the only
//                                        places where business decisions live.

import { runtimeFiles } from './runtime.js';
import naming from './naming.js';

const HEADER = (source) =>
  `// GENERATED by the backend codegen from ${source} — DO NOT EDIT.\n` +
  `// Change the event model and regenerate; edits here are overwritten.\n`;

// Logic-bearing classes (handlers, projectors, repositories, entities) are
// scaffolded once, then owned: a regression inserts model-missing members but
// NEVER overwrites a hand edit, and model drift on an existing member is
// reported as an advisory prompt rather than applied mechanically.
const LOGIC_HEADER = (source) =>
  `// GENERATED by the backend codegen from ${source} — DO NOT EDIT.\n` +
  `// Scaffolded once, then additive: keep hand edits; model drift is reported,\n` +
  `// never applied over them.\n`;

// Deciders are `once`, so they carry the same drift marker as the runtime.
// Bump DECIDER_SCAFFOLD_VERSION only if the SHAPE of a scaffolded decider
// changes (not when the model gains a field — a missing stub is already a loud
// javac error naming the exact method).
//   v2 - command deciders gained the always-present `check(cmd)` precondition seam.
export const DECIDER_SCAFFOLD_VERSION = 2;

const ONCE_HEADER = (what) =>
  `// SCAFFOLDED ONCE by scripts/codegen — this file is YOURS.\n` +
  `// scaffold-version: ${DECIDER_SCAFFOLD_VERSION}\n` +
  `// It holds the hand-written logic for ${what}: preconditions (business rules) in\n` +
  `// check(), and one decision per [bracketed] model field. Drive both in with a test.\n`;

const uniq = (xs) => [...new Set(xs)].filter(Boolean);
const importBlock = (imports) =>
  uniq(imports).sort().map((i) => `import ${i};`).join('\n');

const components = (fields) => fields.map((f) => `${f.javaType} ${f.name}`).join(', ');

// --- collaborators -----------------------------------------------------------
// A collaborator is a constructor dependency of a generated class. The generator
// knows only three things about one: what to declare as a field, how a TEST
// instantiates it, and (optionally) a file to scaffold for it.
//
// It deliberately does NOT know what the dependency MEANS. "Decider" is not a
// concept here — it is merely the collaborator the [bracket] convention happens
// to produce today. A validator, a clock, a sequence or an ID generator would be
// added as another producer of this same shape, touching no emitter and no
// call site, because every emitter below consumes the LIST, never a named flag.
//
//   fieldName          constructor field name (Lombok @RequiredArgsConstructor
//                      derives the ctor signature from declaration order)
//   className          declared type
//   testInstantiation  expression a *Ability uses to build/obtain it. Varies by
//                      kind — `new FooDecider()` for a fresh instance, a shared
//                      static like `FooAbility.FOO_REPOSITORY` for a registered
//                      one — which is exactly why this is per-collaborator data
//                      and not a rule baked into the ability emitter.
//   imports            imports the declaration needs (may be empty/same package)
//   scaffold           optional () => file, emitted alongside the owner
const collaborator = ({ fieldName, className, testInstantiation, imports = [], scaffold = null }) => ({
  fieldName,
  className,
  testInstantiation,
  imports,
  scaffold,
});

const fieldDeclarations = (collaborators) =>
  collaborators.map((c) => `    private final ${c.className} ${c.fieldName};`).join('\n');

const constructorArgs = (collaborators) =>
  collaborators.map((c) => c.testInstantiation).join(', ');

const collaboratorImports = (collaborators) => collaborators.flatMap((c) => c.imports);

const collaboratorScaffolds = (collaborators) =>
  collaborators.filter((c) => c.scaffold).map((c) => c.scaffold());

// --- expression resolution for a target field --------------------------------
// This is where the [bracket] convention pays off: everything derivable is
// derived; anything that is not is DELEGATED to a collaborator. `delegate`
// names the collaborator field and the arguments to pass it — the resolver
// itself has no notion of what that collaborator is for.
function resolveArg(field, { sourceFields, sourceExpr, delegate, fallback }) {
  if (field.convention) return { expr: field.conventionExpr, imports: field.imports };
  if (field.bracketed) {
    return {
      expr: `${delegate.fieldName}.${field.name}(${delegate.args ?? ''})`,
      imports: [],
      delegated: true,
    };
  }
  const match = sourceFields.find((f) => f.name === field.name);
  if (match) return { expr: `${sourceExpr}.${field.name}()`, imports: [] };
  if (fallback) return { expr: fallback(field), imports: [] };
  return null;
}

// --- emitters ----------------------------------------------------------------

function valueObject(vo) {
  const needsList = vo.fields.some((f) => f.javaType.startsWith('List<'));
  const immutable = !needsList;
  const headers = [];
  if (immutable) headers.push('import jakarta.persistence.Embeddable;');
  const imports = [...headers, ...(needsList ? ['import java.util.List;'] : [])];
  return {
    package: vo.package,
    className: vo.className,
    overwrite: true,
    content: `${HEADER('business-definitions-raw.md')}package ${vo.package};

${imports.length ? imports.join('\n') + '\n\n' : ''}${immutable ? '@Embeddable\n' : ''}public record ${vo.className}(${components(vo.fields)}) {
}
`,
  };
}

function event(e, base) {
  const imports = importBlock([
    'java.util.UUID',
    'lombok.Builder',
    `${base}.eventstream.DomainEvent`,
    ...e.fields.flatMap((f) => f.imports),
  ]);
  return {
    package: e.package,
    className: e.className,
    overwrite: true,
    content: `${HEADER('events.md')}package ${e.package};

${imports}

@Builder
public record ${e.className}(UUID aggregateId, ${components(e.fields)}) implements DomainEvent {
    @Override
    public DomainEventType eventType() {
        return DomainEventType.${e.typeEnum};
    }
}
`,
  };
}

function eventType(events, base) {
  const constants = events.map((e) => `    ${e.typeEnum},`).join('\n');
  return {
    package: `${base}.domain.events`,
    className: 'DomainEventType',
    overwrite: true,
    content: `${HEADER('events.md')}package ${base}.domain.events;

public enum DomainEventType {
${constants}
}
`,
  };
}

function command(c) {
  const imports = importBlock(['lombok.Builder', ...c.fields.flatMap((f) => f.imports)]);
  return {
    package: c.package,
    className: c.className,
    overwrite: true,
    content: `${HEADER('commands.md')}package ${c.package};

${imports}

@Builder
public record ${c.className}(${components(c.fields)}) {
}
`,
  };
}

function commandHandler(c, e, base) {
  const args = [];
  const extraImports = [];

  const eventStream = collaborator({
    fieldName: 'eventStream',
    className: 'EventStream',
    testInstantiation: 'EventStreamAbility.INSTANCE',
    imports: [`${base}.eventstream.EventStream`],
  });
  // Produced by the [bracket] convention, consumed as a plain collaborator.
  const decider = collaborator({
    fieldName: 'decider',
    className: c.deciderClassName,
    testInstantiation: `new ${c.deciderClassName}()`,
    scaffold: () => commandDecider(c, e),
  });

  for (const f of e.fields) {
    const r = resolveArg(f, {
      sourceFields: c.fields,
      sourceExpr: 'command',
      delegate: decider,
    });
    if (!r) {
      throw new Error(
        `Model gap: event "${e.id}" field "${f.label}" is not supplied by command "${c.id}" ` +
          `and is not [bracketed]. Either add it to the command or bracket it.`,
      );
    }
    extraImports.push(...r.imports);
    args.push(r.expr);
  }

  // The decider is wired in ALWAYS, not only when a [bracket] delegates to it. It is
  // the single seam where this command's hand-written logic lives — preconditions from
  // business-rules-raw.md as well as [bracketed] decisions. Making the seam a
  // by-product of bracket syntax would leave a rule on an unbracketed command with
  // nowhere to go but a generated file or the model itself, and both are forbidden.
  const collaborators = [eventStream, decider];

  const imports = importBlock([
    'java.util.List',
    'java.util.UUID',
    'lombok.RequiredArgsConstructor',
    'org.springframework.stereotype.Component',
    'org.springframework.transaction.annotation.Transactional',
    'org.springframework.web.bind.annotation.PostMapping',
    'org.springframework.web.bind.annotation.RequestBody',
    'org.springframework.web.bind.annotation.RestController',
    `${base}.eventstream.CommandHandler`,
    `${e.package}.${e.className}`,
    ...collaboratorImports(collaborators),
    ...extraImports,
  ]);

  const argList = args.map((a) => `                ${a}`).join(',\n');

  return {
    package: c.package,
    className: c.handlerClassName,
    overwrite: true,
    logic: true,
    content: `${LOGIC_HEADER('commands.md + events.md')}package ${c.package};

${imports}

@RestController
@Component
@Transactional
@RequiredArgsConstructor
public class ${c.handlerClassName} implements CommandHandler<${c.className}> {

${fieldDeclarations(collaborators)}

    @PostMapping("${c.postMapping}")
    @Override
    public UUID handle(@RequestBody ${c.className} command) {
        decider.check(command);
        var aggregateId = UUID.randomUUID();
        eventStream.append(List.of(new ${e.className}(
                aggregateId,
${argList})));
        return aggregateId;
    }
}
`,
    collaborators,
  };
}

function commandDecider(c, e) {
  const decided = e.fields.filter((f) => f.bracketed && !f.convention);
  const methods = decided
    .map(
      (f) => `    public ${f.javaType} ${f.name}() {
        throw new UnsupportedOperationException(
                "[${f.label}] on event '${e.id}' is a business decision with no GWT scenario yet");
    }`,
    )
    .join('\n\n');
  // Always emitted, always empty. "No rule yet" is a legitimate steady state, so this
  // does NOT throw — unlike a [bracketed] decision, which is loudly unimplemented.
  // Business rules constraining this command become guard clauses here, driven in by a
  // spec. The generator names no field and knows no rule: the seam is the contract.
  const guard = `    public void check(${c.className} command) {
    }`;
  const body = [guard, methods].filter(Boolean).join('\n\n');
  const imports = importBlock([
    'org.springframework.stereotype.Component',
    ...decided.flatMap((f) => f.imports),
  ]);
  return {
    package: c.package,
    className: c.deciderClassName,
    once: true,
    version: DECIDER_SCAFFOLD_VERSION,
    content: `${ONCE_HEADER(`command "${c.id}"`)}package ${c.package};

${imports}

@Component
public class ${c.deciderClassName} {

${body}
}
`,
  };
}

function readModel(rm) {
  const imports = importBlock(rm.fields.flatMap((f) => f.imports));
  return {
    package: rm.package,
    className: rm.className,
    overwrite: true,
    content: `${HEADER('readmodels.md')}package ${rm.package};

${imports ? imports + '\n\n' : ''}public record ${rm.className}(${components(rm.fields)}) {
}
`,
  };
}

function projector(rm, eventsById, base) {
  const extraImports = [];

  const eventStream = collaborator({
    fieldName: 'eventStream',
    className: 'EventStream',
    testInstantiation: 'EventStreamAbility.INSTANCE',
    imports: [`${base}.eventstream.EventStream`],
  });
  const decider = collaborator({
    fieldName: 'decider',
    className: rm.deciderClassName,
    testInstantiation: `new ${rm.deciderClassName}()`,
    scaffold: () => projectionDecider(rm, eventsById),
  });

  let delegated = false;
  const applies = rm.subscribes.map((eid) => {
    const e = eventsById.get(eid);
    const args = rm.fields.map((f) => {
      const r = resolveArg(f, {
        sourceFields: e.fields,
        sourceExpr: 'event',
        delegate: { ...decider, args: 'state, event' },
        fallback: (field) => `state == null ? null : state.${field.name}()`,
      });
      if (r.delegated) delegated = true;
      extraImports.push(...r.imports);
      return r.expr;
    });
    extraImports.push(`${e.package}.${e.className}`);
    return `    @Override
    public ${rm.className} apply(${rm.className} state, ${e.className} event) {
        return new ${rm.className}(
${args.map((a) => `                ${a}`).join(',\n')});
    }`;
  });

  const collaborators = delegated ? [eventStream, decider] : [eventStream];

  const imports = importBlock([
    'java.util.UUID',
    'lombok.RequiredArgsConstructor',
    'org.springframework.stereotype.Component',
    'org.springframework.web.bind.annotation.GetMapping',
    'org.springframework.web.bind.annotation.PathVariable',
    'org.springframework.web.bind.annotation.RestController',
    `${base}.eventstream.StateProjector`,
    ...collaboratorImports(collaborators),
    ...extraImports,
  ]);

  return {
    package: rm.package,
    className: rm.projectorClassName,
    overwrite: true,
    logic: true,
    collaborators,
    content: `${LOGIC_HEADER('readmodels.md + events.md')}package ${rm.package};

${imports}

@RestController
@Component
@RequiredArgsConstructor
public class ${rm.projectorClassName} implements StateProjector<${rm.className}> {

${fieldDeclarations(collaborators)}

    @GetMapping("${rm.getMapping}")
    public ${rm.className} ${rm.getterMethod}(@PathVariable UUID aggregateId) {
        return hydrate(null, eventStream.findAllById(aggregateId));
    }

${applies.join('\n\n')}
}
`,
  };
}

function projectionDecider(rm, eventsById) {
  const methods = [];
  const imports = ['org.springframework.stereotype.Component'];
  for (const eid of rm.subscribes) {
    const e = eventsById.get(eid);
    for (const f of rm.fields.filter((x) => x.bracketed && !x.convention)) {
      imports.push(...f.imports, `${e.package}.${e.className}`);
      methods.push(`    public ${f.javaType} ${f.name}(${rm.className} state, ${e.className} event) {
        throw new UnsupportedOperationException(
                "[${f.label}] on read model '${rm.id}' is a projection decision with no GWT scenario yet");
    }`);
    }
  }
  return {
    package: rm.package,
    className: rm.deciderClassName,
    once: true,
    version: DECIDER_SCAFFOLD_VERSION,
    content: `${ONCE_HEADER(`read model "${rm.id}"`)}package ${rm.package};

${importBlock(imports)}

@Component
public class ${rm.deciderClassName} {

${methods.join('\n\n')}
}
`,
  };
}

function stateProjector(events, base) {
  const cases = events
    .map((e) => `            case ${e.typeEnum} -> apply(state, (${e.className}) event);`)
    .join('\n');
  const defaults = events
    .map(
      (e) => `    default S apply(S state, ${e.className} event) {
        return state;
    }`,
    )
    .join('\n\n');
  const imports = importBlock([
    'java.util.Collection',
    ...events.map((e) => `${e.package}.${e.className}`),
  ]);
  return {
    package: `${base}.eventstream`,
    className: 'StateProjector',
    overwrite: true,
    content: `${HEADER('events.md')}package ${base}.eventstream;

${imports}

public interface StateProjector<S> {

    default S hydrate(S state, Collection<DomainEvent> events) {
        return events.stream().reduce(state, this::apply, (_, s2) -> s2);
    }

    private S apply(S state, DomainEvent event) {
        return switch (event.eventType()) {
${cases}
            default -> state;
        };
    }

${defaults}
}
`,
  };
}

function serdeWrapper(e, base) {
  return {
    package: e.serdePackage,
    className: e.serdeClassName,
    overwrite: true,
    content: `${HEADER('events.md')}package ${e.serdePackage};

${importBlock([
  'com.fasterxml.jackson.annotation.JsonTypeName',
  `${base}.domain.events.DomainEventType`,
  `${e.package}.${e.className}`,
])}

@JsonTypeName("${e.typeEnum}")
public record ${e.serdeClassName}(${e.className} event) implements DomainEventSerdeWrapper {
    @Override
    public DomainEventType getEventType() {
        return DomainEventType.${e.typeEnum};
    }
}
`,
  };
}

function serdeRegistry(events, base) {
  const subTypes = events
    .map((e) => `        @JsonSubTypes.Type(value = ${e.serdeClassName}.class, name = "${e.typeEnum}"),`)
    .join('\n');
  return {
    package: `${base}.infrastructure`,
    className: 'DomainEventSerdeWrapper',
    overwrite: true,
    content: `${HEADER('events.md')}package ${base}.infrastructure;

${importBlock([
  'com.fasterxml.jackson.annotation.JsonIgnoreProperties',
  'com.fasterxml.jackson.annotation.JsonInclude',
  'com.fasterxml.jackson.annotation.JsonSubTypes',
  'com.fasterxml.jackson.annotation.JsonTypeInfo',
  `${base}.domain.events.DomainEventType`,
  `${base}.eventstream.DomainEvent`,
])}

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "eventType")
@JsonSubTypes({
${subTypes}
})
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public interface DomainEventSerdeWrapper {
    DomainEventType getEventType();
    DomainEvent event();
}
`,
  };
}

function serde(events, base) {
  const cases = events
    .map((e) => `            case ${e.typeEnum} -> new ${e.serdeClassName}((${e.className}) event);`)
    .join('\n');
  return {
    package: `${base}.infrastructure`,
    className: 'DomainEventSerde',
    overwrite: true,
    content: `${HEADER('events.md')}package ${base}.infrastructure;

${importBlock([`${base}.eventstream.DomainEvent`, ...events.map((e) => `${e.package}.${e.className}`)])}

public final class DomainEventSerde {

    private DomainEventSerde() {
    }

    public static DomainEventSerdeWrapper serialize(DomainEvent event) {
        return switch (event.eventType()) {
${cases}
            default -> throw new IllegalArgumentException("No serde wrapper for " + event.eventType());
        };
    }
}
`,
  };
}

// --- test abilities (mechanical DSL, generator-owned) ------------------------

// Domain-independent on purpose. It must NOT name any slice: a persisting projector
// is wired by its OWN sibling ability calling `register`, so adding a `:Key` read
// model never edits this file and each component owns its own test utility.
function eventStreamAbility(base) {
  return {
    test: true,
    package: `${base}.eventstream`,
    className: 'EventStreamAbility',
    overwrite: true,
    content: `${HEADER('the event stream infrastructure')}package ${base}.eventstream;

${importBlock([
  'java.util.List',
  'java.util.concurrent.CopyOnWriteArrayList',
  `${base}.infrastructure.DomainEventInMemoryRepository`,
  `${base}.infrastructure.EventStreamImpl`,
])}

public interface EventStreamAbility {

    List<PersistingProjector> PROJECTORS = new CopyOnWriteArrayList<>();
    List<Runnable> PROJECTION_RESETS = new CopyOnWriteArrayList<>();

    DomainEventInMemoryRepository REPOSITORY = new DomainEventInMemoryRepository();
    EventStream INSTANCE = new EventStreamImpl(REPOSITORY, PROJECTORS);

    static <P extends PersistingProjector> P register(P projector, Runnable reset) {
        EventStreamAbility.PROJECTORS.add(projector);
        EventStreamAbility.PROJECTION_RESETS.add(reset);
        return projector;
    }

    default EventStream getEventStream() {
        return EventStreamAbility.INSTANCE;
    }

    default void reset_event_stream() {
        EventStreamAbility.REPOSITORY.deleteAll();
        EventStreamAbility.PROJECTION_RESETS.forEach(Runnable::run);
    }
}
`,
  };
}

function commandAbility(c, base, collaborators) {
  return {
    test: true,
    package: c.package,
    className: c.abilityClassName,
    overwrite: true,
    content: `${HEADER('commands.md')}package ${c.package};

${importBlock([
  'java.util.UUID',
  'java.util.function.Consumer',
  `${base}.eventstream.EventStreamAbility`,
])}

public interface ${c.abilityClassName} extends EventStreamAbility {

    ${c.handlerClassName} INSTANCE =
            new ${c.handlerClassName}(${constructorArgs(collaborators)});

    default ${c.handlerClassName} get${c.handlerClassName}() {
        return ${c.abilityClassName}.INSTANCE;
    }

    default UUID ${c.dslMethod}(Consumer<${c.className}.${c.className}Builder> testCase) {
        var cmd = ${c.className}.builder();
        testCase.accept(cmd);
        return get${c.handlerClassName}().handle(cmd.build());
    }
}
`,
  };
}

function projectorAbility(rm, base, collaborators) {
  return {
    test: true,
    package: rm.package,
    className: rm.abilityClassName,
    overwrite: true,
    content: `${HEADER('readmodels.md')}package ${rm.package};

${importBlock([
  'java.util.UUID',
  'java.util.function.Predicate',
  `${base}.eventstream.EventStreamAbility`,
])}

public interface ${rm.abilityClassName} extends EventStreamAbility {

    ${rm.projectorClassName} INSTANCE =
            new ${rm.projectorClassName}(${constructorArgs(collaborators)});

    default ${rm.projectorClassName} get${rm.projectorClassName}() {
        return ${rm.abilityClassName}.INSTANCE;
    }

    default boolean ${rm.dslMethod}(UUID aggregateId, Predicate<${rm.className}> testCase) {
        return testCase.test(get${rm.projectorClassName}().${rm.getterMethod}(aggregateId));
    }
}
`,
  };
}

// --- persisting read models (<aggregate>:Key) --------------------------------
// One row per aggregate, keyed by aggregateId, advanced on append. Unlike an
// on-demand projection it can be listed across aggregates, which is the whole
// reason the model marks it with ":Key".

function readModelEntity(rm) {
  const keyed = rm.keyFields.length > 0;
  const keyNames = new Set(rm.keyFields.map((f) => f.name));
  const nonKeyFields = rm.fields.filter((f) => !keyNames.has(f.name));
  // A value object with a list attribute cannot be a JPA embeddable and is stored as
  // JSON; a scalar-only value object is embedded and flattened into prefixed columns.
  const jsonFields = nonKeyFields.filter((f) => f.valueObject && !f.embeds);
  const importBlockList = [
    ...(keyed ? ['jakarta.persistence.EmbeddedId'] : ['java.util.UUID', 'jakarta.persistence.Id']),
    'jakarta.persistence.AttributeOverride',
    'jakarta.persistence.AttributeOverrides',
    'jakarta.persistence.Column',
    'jakarta.persistence.Embedded',
    'jakarta.persistence.Entity',
    'jakarta.persistence.Table',
    'lombok.AccessLevel',
    'lombok.AllArgsConstructor',
    'lombok.Getter',
    'lombok.NoArgsConstructor',
    'lombok.Setter',
    ...(jsonFields.length
      ? ['org.hibernate.annotations.JdbcTypeCode', 'org.hibernate.type.SqlTypes']
      : []),
    ...nonKeyFields.flatMap((f) => f.imports),
  ];
  const idField = keyed
    ? `
    @EmbeddedId
    private ${rm.idClassName} id;
`
    : `
    @Id
    private UUID aggregateId;
`;
  const columns = nonKeyFields
    .map((f) => {
      if (f.embeds) {
        const prefix = naming.snake(f.name);
        const overrides = f.attrs
          .map(
            (a) =>
              `        @AttributeOverride(name = "${a.name}", ` +
              `column = @Column(name = "${prefix}_${naming.snake(a.name)}"))`,
          )
          .join(',\n');
        return `    @Embedded\n    @AttributeOverrides({\n${overrides}\n    })\n    private ${f.javaType} ${f.name};`;
      }
      if (f.valueObject) {
        return `    @JdbcTypeCode(SqlTypes.JSON)\n    private ${f.javaType} ${f.name};`;
      }
      return `    private ${f.javaType} ${f.name};`;
    })
    .join('\n');
  // toReadModel passes fields in READ MODEL order: key fields come from id.<field>(),
  // everything else from the entity's own fields.
  const readModelArgs = rm.fields.map((f) => (keyed && keyNames.has(f.name) ? `id.${f.name}()` : f.name));
  return {
    package: rm.package,
    className: rm.entityClassName,
    overwrite: true,
    logic: true,
    content: `${LOGIC_HEADER('readmodels.md')}package ${rm.package};

${importBlock(importBlockList)}

@Entity
@Table(name = "${rm.tableName}")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class ${rm.entityClassName} {
${idField}
${columns}

    public ${rm.className} toReadModel() {
        return new ${rm.className}(${readModelArgs.join(', ')});
    }
}
`,
  };
}

// Composite (natural) id of a persisting read model whose `:Key` fields compose it.
// Only emitted when the model actually marks one or more fields `:Key`; otherwise the
// entity stays keyed by the aggregate id.
function readModelKey(rm) {
  const components = rm.keyFields
    .map((f) =>
      f.embeds
        ? keyRecordComponent(f)
        : `    ${f.javaType} ${f.name}`,
    )
    .join(',\n');
  return {
    package: rm.package,
    className: rm.idClassName,
    overwrite: true,
    content: `${HEADER('readmodels.md')}package ${rm.package};

${importBlock(keyRecordImports(rm))}

@Embeddable
public record ${rm.idClassName}(
${components}) {
}
`,
  };
}

function keyRecordComponent(f) {
  const prefix = naming.snake(f.name);
  const overrides = f.attrs
    .map(
      (a) =>
        `            @AttributeOverride(name = "${a.name}", ` +
        `column = @Column(name = "${prefix}_${naming.snake(a.name)}"))`,
    )
    .join(',\n');
  return `    @Embedded
    @AttributeOverrides({
${overrides}
    })
    private ${f.javaType} ${f.name}`;
}

function keyRecordImports(rm) {
  const set = new Set(['jakarta.persistence.Embeddable']);
  let hasEmbeddedStyle = false;
  for (const f of rm.keyFields) {
    if (f.embeds) {
      hasEmbeddedStyle = true;
      for (const i of f.imports) set.add(i);
    }
  }
  if (hasEmbeddedStyle) {
    set.add('jakarta.persistence.AttributeOverride');
    set.add('jakarta.persistence.AttributeOverrides');
    set.add('jakarta.persistence.Column');
    set.add('jakarta.persistence.Embedded');
  }
  return [...set];
}


// Every searchable field of a persisting read model, as the shared vocabulary the
// server-side repository search and its test double both speak. A scalar String field
// is searchable by its own name (policyNumber); an embedded (scalar-only) value object
// field searches per attribute (policyHolder.name). A value object carrying a list is
// JSON, not embeddable, and is not searchable by an individual element.
function searchableFields(rm) {
  const out = [];
  for (const f of rm.fields) {
    if (f.embeds) {
      const owner = `e.get${naming.cap(f.name)}()`;
      for (const a of f.attrs) {
        out.push({
          key: `${f.name}.${a.name}`,
          criteriaPath: `root.get("${f.name}").get("${a.name}")`,
          ownerGetter: owner,
          ownerNullGuard: `${owner} == null || `,
          // Record embeddables are accessed by their component name, e.g. .name()
          attrAccessor: `.${a.name}()`,
        });
      }
    } else if (!f.valueObject) {
      out.push({
        key: f.name,
        criteriaPath: `root.get("${f.name}")`,
        ownerGetter: `e.get${naming.cap(f.name)}()`,
        ownerNullGuard: '',
        attrAccessor: '',
      });
    }
  }
  return out;
}

function readModelRepository(rm) {
  const keyed = rm.keyFields.length > 0;
  const idType = keyed ? rm.idClassName : 'UUID';
  const repoImports = ['java.util.List', 'java.util.Map', 'java.util.Optional', ...(keyed ? [] : ['java.util.UUID'])];
  return {
    package: rm.package,
    className: rm.repositoryClassName,
    overwrite: true,
    logic: true,
    content: `${LOGIC_HEADER('readmodels.md')}package ${rm.package};

${importBlock(repoImports)}

public interface ${rm.repositoryClassName} {
    ${rm.entityClassName} save(${rm.entityClassName} entity);
    Optional<${rm.entityClassName}> findById(${idType} id);
    List<${rm.entityClassName}> findAll();
    List<${rm.entityClassName}> findAllBySearch(Map<String, String> search);
    void deleteAll();
}
`,
  };
}

function readModelJpaRepository(rm) {
  const keyed = rm.keyFields.length > 0;
  const idType = keyed ? rm.idClassName : 'UUID';
  const searchables = searchableFields(rm);
  const specImports = searchables.length
    ? [
        'java.util.ArrayList',
        'jakarta.persistence.criteria.Predicate',
        'org.springframework.data.jpa.domain.Specification',
        'org.springframework.data.jpa.repository.JpaSpecificationExecutor',
      ]
    : [];
  const specSearch = searchables
    .map(
      (s) =>
        `            if (search.get("${s.key}") != null && !search.get("${s.key}").isBlank()) {\n` +
        `                predicates.add(cb.like(cb.lower(${s.criteriaPath}), "%" + search.get("${s.key}").toLowerCase() + "%"));\n` +
        `            }`,
    )
    .join('\n');
  return {
    package: rm.package,
    className: rm.jpaRepositoryClassName,
    overwrite: true,
    logic: true,
    content: `${LOGIC_HEADER('readmodels.md')}package ${rm.package};

${importBlock(['java.util.List', 'java.util.Map', ...(keyed ? [] : ['java.util.UUID']), 'org.springframework.data.jpa.repository.JpaRepository', ...specImports])}

public interface ${rm.jpaRepositoryClassName}
        extends ${rm.repositoryClassName},
                JpaRepository<${rm.entityClassName}, ${idType}>${searchables.length ? ',\n                JpaSpecificationExecutor<' + rm.entityClassName + '>' : ''} {

    @Override
    default List<${rm.entityClassName}> findAllBySearch(Map<String, String> search) {
        Specification<${rm.entityClassName}> spec = (root, query, cb) -> {
            var predicates = new ArrayList<Predicate>();
${specSearch}
            return cb.and(predicates.toArray(new Predicate[0]));
        };
        return findAll(spec);
    }
}
`,
  };
}

function readModelInMemoryRepository(rm) {
  const keyed = rm.keyFields.length > 0;
  const idType = keyed ? rm.idClassName : 'UUID';
  const idExpr = keyed ? 'entity.getId()' : 'entity.getAggregateId()';
  const searchables = searchableFields(rm);
  const cases = searchables
    .map(
      (s) =>
        `                case "${s.key}" -> {
                    if (value.isBlank() || ${s.ownerNullGuard}${s.ownerGetter}${s.attrAccessor} == null
                            || !${s.ownerGetter}${s.attrAccessor}.toLowerCase().contains(value.toLowerCase())) {
                        return false;
                    }
                }`,
    )
    .join('\n');
  const search = searchables.length
    ? `
    @Override
    public List<${rm.entityClassName}> findAllBySearch(Map<String, String> search) {
        return entities.values().stream().filter(e -> {
            for (var entry : search.entrySet()) {
                String value = entry.getValue() == null ? "" : entry.getValue();
                switch (entry.getKey()) {
${cases}
                }
            }
            return true;
        }).toList();
    }`
    : '';
  return {
    test: true,
    package: rm.package,
    className: rm.inMemoryRepositoryClassName,
    overwrite: true,
    logic: true,
    content: `${LOGIC_HEADER('readmodels.md')}package ${rm.package};

${importBlock([
  'java.util.LinkedHashMap',
  'java.util.List',
  'java.util.Map',
  'java.util.Optional',
  ...(keyed ? [] : ['java.util.UUID']),
])}

public class ${rm.inMemoryRepositoryClassName} implements ${rm.repositoryClassName} {

    private final Map<${idType}, ${rm.entityClassName}> entities = new LinkedHashMap<>();

    @Override
    public ${rm.entityClassName} save(${rm.entityClassName} entity) {
        entities.put(${idExpr}, entity);
        return entity;
    }

    @Override
    public Optional<${rm.entityClassName}> findById(${idType} id) {
        return Optional.ofNullable(entities.get(id));
    }

    @Override
    public List<${rm.entityClassName}> findAll() {
        return List.copyOf(entities.values());
    }
${search}
    @Override
    public void deleteAll() {
        entities.clear();
    }
}
`,
  };
}


function persistingProjector(rm, eventsById, base) {
  const extraImports = [];
  const keyed = rm.keyFields.length > 0;
  const keyNames = new Set(rm.keyFields.map((f) => f.name));

  // The repository is a collaborator like any other — note its
  // testInstantiation is a shared registered static, not `new ...()`. Before
  // collaborators were a list, this difference forced it to be special-cased
  // separately from the decider in every emitter.
  const repository = collaborator({
    fieldName: 'repository',
    className: rm.repositoryClassName,
    testInstantiation: `${rm.abilityClassName}.${rm.repositoryConstant}`,
  });
  const decider = collaborator({
    fieldName: 'decider',
    className: rm.deciderClassName,
    testInstantiation: `new ${rm.deciderClassName}()`,
    scaffold: () => projectionDecider(rm, eventsById),
  });

  let delegated = false;
  const applies = rm.subscribes.map((eid) => {
    const e = eventsById.get(eid);
    const args = rm.fields.map((f) => {
      const r = resolveArg(f, {
        sourceFields: e.fields,
        sourceExpr: 'event',
        delegate: { ...decider, args: 'state, event' },
        fallback: (field) => `state == null ? null : state.${field.name}()`,
      });
      if (r.delegated) delegated = true;
      extraImports.push(...r.imports);
      return r.expr;
    });
    extraImports.push(`${e.package}.${e.className}`);

    // For keyed read models, build the composite key from projected key fields.
    const entitySave = keyed
      ? `repository.save(new ${rm.entityClassName}(new ${rm.idClassName}(${rm.keyFields.map((f) => `projected.${f.name}()`).join(', ')}), ${rm.fields.filter((f) => !keyNames.has(f.name)).map((f) => `projected.${f.name}()`).join(', ')}));`
      : `repository.save(new ${rm.entityClassName}(event.aggregateId(), ${rm.fields.map((f) => `projected.${f.name}()`).join(', ')}));`;

    return `    @Override
    public ${rm.className} apply(${rm.className} state, ${e.className} event) {
        var projected = new ${rm.className}(
${args.map((a) => `                ${a}`).join(',\n')});
        ${entitySave}
        return projected;
    }`;
  });

  // For keyed read models, build the composite key from event fields for the
  // state lookup in project(). Key fields must be passthrough from the event.
  const projectKey = keyed
    ? `new ${rm.idClassName}(${rm.keyFields.map((f) => `event.${f.name}()`).join(', ')})`
    : 'event.aggregateId()';
  const projectIdType = keyed ? rm.idClassName : 'UUID';

  const collaborators = delegated ? [repository, decider] : [repository];

  const imports = importBlock([
    'java.util.List',
    'java.util.Map',
    ...(keyed ? [] : ['java.util.UUID']),
    'lombok.RequiredArgsConstructor',
    'org.springframework.stereotype.Component',
    'org.springframework.web.bind.annotation.GetMapping',
    'org.springframework.web.bind.annotation.RequestParam',
    'org.springframework.web.bind.annotation.RestController',
    `${base}.eventstream.DomainEvent`,
    `${base}.eventstream.PersistingProjector`,
    `${base}.eventstream.StateProjector`,
    ...collaboratorImports(collaborators),
    ...extraImports,
  ]);

  return {
    package: rm.package,
    className: rm.projectorClassName,
    overwrite: true,
    logic: true,
    collaborators,
    content: `${LOGIC_HEADER('readmodels.md + events.md')}package ${rm.package};

${imports}

@RestController
@Component
@RequiredArgsConstructor
public class ${rm.projectorClassName}
        implements StateProjector<${rm.className}>, PersistingProjector {

${fieldDeclarations(collaborators)}

    @GetMapping("${rm.getMapping}")
    public List<${rm.className}> ${rm.getterMethod}(@RequestParam Map<String, String> search) {
        return repository.findAllBySearch(search).stream()
                .map(${rm.entityClassName}::toReadModel)
                .toList();
    }

    @Override
    public void project(DomainEvent event) {
        var state = repository.findById(${projectKey})
                .map(${rm.entityClassName}::toReadModel)
                .orElse(null);
        hydrate(state, List.of(event));
    }

${applies.join('\n\n')}
}
`,
  };
}

function persistingProjectorAbility(rm, base, collaborators) {
  return {
    test: true,
    package: rm.package,
    className: rm.abilityClassName,
    overwrite: true,
    content: `${HEADER('readmodels.md')}package ${rm.package};

${importBlock([
  'java.util.List',
  'java.util.Map',
  'java.util.function.Predicate',
  `${base}.eventstream.EventStreamAbility`,
])}

public interface ${rm.abilityClassName} extends EventStreamAbility {

    ${rm.inMemoryRepositoryClassName} ${rm.repositoryConstant} = new ${rm.inMemoryRepositoryClassName}();

    ${rm.projectorClassName} INSTANCE = EventStreamAbility.register(
            new ${rm.projectorClassName}(${constructorArgs(collaborators)}),
            ${rm.abilityClassName}.${rm.repositoryConstant}::deleteAll);

    default ${rm.projectorClassName} get${rm.projectorClassName}() {
        return ${rm.abilityClassName}.INSTANCE;
    }

    default boolean ${rm.dslMethod}(Predicate<List<${rm.className}>> testCase) {
        return testCase.test(get${rm.projectorClassName}().${rm.getterMethod}(Map.of()));
    }

    default boolean ${rm.dslMethod}(Map<String, String> search, Predicate<List<${rm.className}>> testCase) {
        return testCase.test(get${rm.projectorClassName}().${rm.getterMethod}(search));
    }
}
`,
  };
}

// --- orchestration -----------------------------------------------------------

export function emit(model) {
  const base = model.meta.basePackage;
  const eventsById = new Map(model.events.map((e) => [e.id, e]));
  const files = [];

  // domain-independent runtime (scaffolded once, then the project's)
  runtimeFiles(base).forEach((f) => files.push(f));

  model.valueObjects.forEach((vo) => files.push(valueObject(vo)));
  model.events.forEach((e) => files.push(event(e, base), serdeWrapper(e, base)));
  files.push(eventType(model.events, base));
  files.push(stateProjector(model.events, base));
  files.push(serdeRegistry(model.events, base));
  files.push(serde(model.events, base));
  files.push(eventStreamAbility(base));

  // A slice emits its owner, whatever files its collaborators bring with them,
  // and its ability — with no branch anywhere on what KIND of collaborator it
  // is. A new collaborator kind plugs in by being produced above; nothing here
  // changes.
  for (const c of model.commands) {
    const e = eventsById.get(c.producesId);
    const handler = commandHandler(c, e, base);
    files.push(command(c), handler);
    files.push(...collaboratorScaffolds(handler.collaborators));
    files.push(commandAbility(c, base, handler.collaborators));
  }

  for (const rm of model.readModels) {
    if (rm.keyed) {
      const p = persistingProjector(rm, eventsById, base);
      files.push(
        readModel(rm),
        readModelEntity(rm),
        readModelRepository(rm),
        readModelJpaRepository(rm),
        readModelInMemoryRepository(rm),
        p,
      );
      if (rm.keyFields.length > 0) {
        files.push(readModelKey(rm));
      }
      files.push(...collaboratorScaffolds(p.collaborators));
      files.push(persistingProjectorAbility(rm, base, p.collaborators));
      continue;
    }
    const p = projector(rm, eventsById, base);
    files.push(readModel(rm), p);
    files.push(...collaboratorScaffolds(p.collaborators));
    files.push(projectorAbility(rm, base, p.collaborators));
  }

  return files;
}

// Exported for unit tests. The collaborator helpers are the generic seam that
// replaced the old `needsDecider` flag, so they are worth pinning down: a
// regression here silently changes every generated constructor signature.
export {
  collaborator,
  fieldDeclarations,
  constructorArgs,
  collaboratorImports,
  collaboratorScaffolds,
  resolveArg,
  commandHandler,
  command,
  commandDecider,
  valueObject,
  readModelEntity,
  readModelKey,
  readModelRepository,
  readModelJpaRepository,
  readModelInMemoryRepository,
  persistingProjector,
  persistingProjectorAbility,
};
