// Model markdown -> normalised model.json. Pure parsing; no LLM, no filesystem
// discovery beyond reading the declared model files.
//
// Grammar (line-oriented):
//   ## <kebab-id>            starts an element
//   Name: <human name>
//   Produces: <event-id>     (commands)
//   Subscribes: <e1>, <e2>   (read models)
//   <aggregate>:Id           on-demand read model: hydrated from the stream per request
//   <aggregate>:Key          persisting read model: JPA entity keyed by the aggregate id,
//                            updated on append, listable across aggregates
//   * field name             plain payload attribute (passthrough)
//
// The <aggregate>:Id|:Key line is itself an attribute: every read model implicitly
// carries a first component `<aggregate>Id` (or `Key`, UUID) equal to the event's
// aggregateId. It is never spelled out as `* policy id` — an explicit same-name
// line is absorbed (see injectIdentity).
//   * field name?            search criterion field (generates query parameters)
//   * field name??           search-ONLY criterion (read model only): a query
//                            parameter with NO stored/projected value at all — it
//                            is never a field on the entity, never persisted, never
//                            part of the response. Matching is a hand-written Java
//                            predicate applied to the query result AFTER it comes
//                            back from the repository (see projectionDecider /
//                            persistingProjector) — never a DB column/Specification.
//   * [field name]           system-generated/decided attribute
//   * [field name]:uuid|now  system-generated by convention (no decision needed)

import fs from 'node:fs';
import path from 'node:path';
import naming from './naming.js';

const CONVENTIONS = {
  uuid: { javaType: 'UUID', expr: 'UUID.randomUUID()', imports: ['java.util.UUID'] },
  now: { javaType: 'Instant', expr: 'Instant.now()', imports: ['java.time.Instant'] },
};

function parseSections(text) {
  const sections = [];
  let current = null;
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (line.startsWith('## ')) {
      current = { id: line.slice(3).trim(), props: {}, fields: [], searchOnlyFields: [], headerLines: [], aggregate: null, keyed: false };
      sections.push(current);
      continue;
    }
    if (!current || !line || line.startsWith('#')) continue;

    const field = line.match(/^\*\s+(.+)$/);
    if (field) {
      const trimmed = field[1].trim();
      // "??" (checked before the single-"?" case) is a search-only criterion: it
      // never becomes a projected/persisted field, so it's kept out of
      // `current.fields` entirely — see parseSearchOnlyField.
      if (trimmed.endsWith('??')) {
        current.searchOnlyFields.push(parseSearchOnlyField(trimmed));
      } else {
        current.fields.push(parseField(trimmed));
      }
      continue;
    }
    // `foo:Id` -> on-demand, `foo:Key` -> persisting. Both name the same aggregate;
    // only the projection strategy differs, so both must be caught before the generic
    // `Prop: value` rule below (otherwise `policy:Key` silently becomes a property).
    //
    // More than one such line is allowed on a READ MODEL only: when a single line's
    // name does not match the subscribed event's aggregate, every line is instead a
    // NAMED KEY ATTRIBUTE — a dotted/camelCase path into one of the read model's own
    // value-object fields (e.g. `policyHolderName:Key` -> the `name` attribute of a
    // `* policy holder` field), letting a composite key pick individual attributes
    // instead of an entire nested value object. Resolved in resolveReadModelKeys()
    // once fields are decorated, because that resolution needs to know the read
    // model's own fields and its subscribed events' aggregate — neither known here.
    // `current.aggregate`/`.keyed` keep the LAST line for any code path that only
    // ever expects the classic single-line form (events); read models re-resolve
    // both from `headerLines` instead of trusting these two.
    const aggregate = line.match(/^([A-Za-z][\w -]*):(Id|Key)$/);
    if (aggregate) {
      current.headerLines.push({ name: aggregate[1].trim(), mode: aggregate[2] });
      current.aggregate = aggregate[1].trim();
      current.keyed = aggregate[2] === 'Key';
      continue;
    }
    const prop = line.match(/^([A-Za-z]+):\s*(.+)$/);
    if (prop) current.props[prop[1].toLowerCase()] = prop[2].trim();
  }
  return sections;
}

function parseField(raw) {
  let searchable = false;
  if (raw.endsWith('?')) {
    searchable = true;
    raw = raw.slice(0, -1).trim();
  }
  // [policy number]:uuid  |  [policy number]  |  policy holder  |  policy number:Key
  // A trailing `:Key` marks the field as part of a persisting read model's composite
  // (natural) id; it is mutually exclusive with a [bracket] and a :convention.
  const keyMatch = raw.match(/^(.*?):Key$/);
  if (keyMatch) {
    const base = parseField(keyMatch[1].trim());
    if (base.bracketed || base.convention) {
      throw new Error(`":Key" goes on a plain field, not a [bracketed]/:convention one ("${raw}")`);
    }
    return { ...base, key: true, searchable: searchable || base.searchable };
  }
  const m = raw.match(/^(\[)?([^\]]+?)(\])?(?::(\w+))?$/);
  if (!m) throw new Error(`Cannot parse field: "${raw}"`);
  const bracketed = Boolean(m[1] && m[3]);
  const label = m[2].trim();
  const convention = m[4] || null;
  if (convention && !CONVENTIONS[convention]) {
    throw new Error(`Unknown convention ":${convention}" on field "${label}". Known: ${Object.keys(CONVENTIONS).join(', ')}`);
  }
  if (convention && !bracketed) {
    throw new Error(`Convention ":${convention}" is only valid on a [bracketed] field ("${label}")`);
  }
  return { label, name: naming.field(label), bracketed, convention, searchable };
}

// A "??" field is a search-only criterion: purely a query parameter with no
// backing entity column, no record component, no place in the JSON response —
// see the grammar comment at the top of this file. It cannot be [bracketed] or
// carry a :convention/:Key (there is no stored value for those to apply to).
function parseSearchOnlyField(raw) {
  const label = raw.slice(0, -2).trim();
  if (/[[\]]/.test(label) || /:\w+$/.test(label)) {
    throw new Error(
      `Search-only criterion "${raw}" cannot be [bracketed] or carry a :convention/:Key — ` +
        `it has no stored value at all, only "* field name??" is valid.`,
    );
  }
  return { label, name: naming.field(label), searchOnly: true };
}

// -- named key attributes: a composite key over CHOSEN nested attributes -----
//
// The classic `<aggregate>:Key` header line always keys a persisting read model by
// the whole aggregate id. A read model whose natural key is one or more SPECIFIC
// attributes of an already-declared value-object field (e.g. only a policy
// holder's name, not their surname) instead uses one `<path>:Key` header line per
// chosen attribute, e.g.:
//
//   ## insured-policies
//   Subscribes: policy-issued
//   policyHolderName:Key
//   * policy holder
//   * [no of policies]
//
// Recognized by exclusion: a single header line whose name matches the
// subscribed event's aggregate is the classic form (parseModel decides that,
// since it alone knows the aggregate); anything else is a named key attribute
// and must resolve to a field already declared on the SAME read model.

/** "policyHolderName" -> ["policy","holder","name"]. A real camelCase splitter —
 * distinct from naming.words(), which only splits on whitespace/hyphen/underscore
 * and would return the whole camelCase token as a single unsplit word. */
function camelWords(name) {
  return String(name)
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .trim()
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean);
}

/**
 * Generic words excluded when checking whether a "??" search-only criterion
 * shares any vocabulary with a read model's own stored fields. Deliberately
 * NOT domain words (see GWTPlugin's ruleCommand: "only generic words, scripts
 * should be generic and can be applied to multiple domains") — the read
 * model's own id/aggregate name is stripped separately below, because a
 * project's convention of prefixing every field with the aggregate name would
 * otherwise make every field trivially "overlap".
 */
const SEARCH_ONLY_STOPWORDS = new Set([
  'a', 'an', 'the', 'of', 'for', 'to', 'in', 'on', 'and', 'or', 'not',
  'is', 'has', 'have', 'be', 'with', 'that', 'must',
]);

function searchOnlyTokenize(text, extraStop) {
  return String(text)
    .toLowerCase()
    .split(/[^a-z]+/)
    .filter((w) => w && !SEARCH_ONLY_STOPWORDS.has(w) && !extraStop.has(w));
}

/**
 * A "??" search-only criterion has no stored value and the decider that
 * implements it gets no collaborator beyond a no-arg constructor — it can only
 * ever compute a match from data the read model's OWN fields (or their
 * value-object attributes) already carry. If a criterion shares not one word
 * with any of them, there is no data path to a correct implementation without
 * either inventing hidden state or reaching outside the model — both are
 * architect decisions, not something to guess in a decider body.
 *
 * A heuristic, not a proof: it only catches the case where NOTHING overlaps at
 * all. A false negative (some overlap exists, but the field still isn't
 * enough to decide the match) is still possible and is exactly what the
 * decider's own stub-throws-until-implemented already guards against.
 *
 * @param {string} readModelId - e.g. "policy-list"
 * @param {object[]} fields - the read model's OWN decorated regular fields
 * @param {{label: string}[]} searchOnlyFields - raw (undecorated) "??" fields
 */
export function requireSearchOnlyFieldsHaveData(readModelId, fields, searchOnlyFields) {
  if (!searchOnlyFields.length) return;
  const aggregateStop = new Set(searchOnlyTokenize(readModelId, new Set()));
  const dataTokens = new Set();
  for (const f of fields) {
    for (const t of searchOnlyTokenize(f.label, aggregateStop)) dataTokens.add(t);
    for (const a of f.attrs || []) {
      for (const t of searchOnlyTokenize(a.name, aggregateStop)) dataTokens.add(t);
    }
  }
  for (const sf of searchOnlyFields) {
    const sfTokens = searchOnlyTokenize(sf.label, aggregateStop);
    const overlap = sfTokens.some((t) => dataTokens.has(t));
    if (!overlap) {
      const stored = fields.map((f) => f.label).join(', ') || '(none)';
      throw new Error(
        `Read model "${readModelId}" declares "??" search-only field "${sf.label}" but none of ` +
          `its stored fields (${stored}) share any word with it. A "??" criterion's decider gets ` +
          `no collaborator beyond a no-arg constructor, so it can only compute a match from data ` +
          `already on this read model — add the underlying data as a regular field (e.g. a value ` +
          `object attribute it can read), or if the match legitimately needs data from elsewhere, ` +
          `that is an architect decision: escalate it, do not invent hidden decider state.`,
      );
    }
  }
}

/**
 * Resolve one named key attribute (e.g. "policyHolderName") to the value-object
 * field and attribute it must be reading from a field's own value object.
 *
 * Deliberately narrow and non-guessing (see README "The generator refuses to
 * guess"): the name's leading words must exactly match an existing field's own
 * label, and the exact remainder must exactly match exactly one of that
 * field's value-object attributes. Zero or multiple matches both return null
 * — the caller turns that into a MODEL ERROR naming the read model and the
 * unresolved path, rather than silently picking one or inventing a field.
 *
 * @param {string} name - the header line's name, e.g. "policyHolderName"
 * @param {object[]} fields - the read model's OWN decorated fields
 * @returns {{field: object, attr: object}|null}
 */export function resolveKeyAttributePath(name, fields) {
  const nameWords = camelWords(name);
  const hits = [];
  for (const field of fields) {
    if (!field.valueObject) continue;
    const fieldWords = camelWords(field.name);
    if (fieldWords.length >= nameWords.length) continue;
    const isPrefix = fieldWords.every((w, i) => w === nameWords[i]);
    if (!isPrefix) continue;
    const remainder = nameWords.slice(fieldWords.length).join('');
    const attr = (field.attrs || []).find((a) => a.name.toLowerCase() === remainder);
    if (attr) hits.push({ field, attr });
  }
  return hits.length === 1 ? hits[0] : null;
}

// The `<aggregate>:Id|:Key` header line is itself a read model attribute: the
// aggregate identity is prepended as the first field (UUID) without the model
// spelling it out. Naming follows the header suffix — `policy:Id` -> `policyId`,
// `policy:Key` -> `policyKey` — and the value is always the event's aggregateId,
// so it can never drift from `attribute:id`/`attribute:key`.
//
// An explicit `* policy id` line is absorbed: plain duplicates disappear, a
// `?` (searchable) or `:Key` marker on it is merged onto the implicit field.
// A [bracketed]/:convention duplicate is a model error — the identity is
// generator-owned, never a decision or a convention.
export function injectIdentity(section, fields) {
  const label = `${section.aggregate} ${section.keyed ? 'key' : 'id'}`;
  const name = naming.field(label);
  const explicit = fields.find((f) => f.name === name);
  if (explicit && (explicit.bracketed || explicit.convention)) {
    throw new Error(
      `"${label}" is the read model's identity attribute (from "${section.aggregate}:" ` +
        `header) and is added implicitly — it cannot be [bracketed] or carry a :convention`,
    );
  }
  const identity = {
    label,
    name,
    bracketed: false,
    convention: null,
    searchable: explicit?.searchable ?? false,
    ...(explicit?.key ? { key: true } : {}),
    identity: true,
    javaType: 'UUID',
    imports: ['java.util.UUID'],
    conventionExpr: null,
  };
  return [identity, ...fields.filter((f) => f.name !== name)];
}

// ---- business definitions -------------------------------------------------

// Bullets under "# examples" are sample VALUES (test-data defaults for
// TestDataAbility), never attributes. Only bullets outside that section
// describe the concept's structure.
function parseDefinitions(text) {
  const defs = [];
  for (const block of text.split(/^-{3,}\s*$/m)) {
    const nameLine = block.match(/^#\s*name\s+(.+)$/m);
    if (!nameLine) continue;
    const attrs = [];
    const examples = [];
    let inExamples = false;
    for (const line of block.split('\n')) {
      const heading = line.match(/^#\s*(\w+)/);
      if (heading) inExamples = heading[1].toLowerCase() === 'examples';
      const bullet = line.match(/^\*\s+(.+)$/);
      if (!bullet) continue;
      (inExamples ? examples : attrs).push(bullet[1].trim());
    }
    defs.push({ name: nameLine[1].trim(), attributes: attrs, examples });
  }
  return defs;
}

// A concept WITH listed attributes becomes a value object; without, a String.
// Both carry the definition's examples: TestDataPlugin derives test-data
// defaults from them.
function resolveTypes(defs, base) {
  const byKey = new Map();
  const valueObjects = [];
  for (const def of defs) {
    const key = naming.words(def.name).join(' ');
    if (def.attributes.length === 0) {
      byKey.set(key, { javaType: 'String', imports: [], examples: def.examples });
      continue;
    }
    const vo = naming.valueObject(base, def.name);
    const attrs = def.attributes.map((a) => ({
      name: naming.field(a),
      // a "... list" attribute is a list of names; everything else is a plain String
      javaType: /\blist$/i.test(a.trim()) ? 'List<String>' : 'String',
    }));
    // A value object with only scalar String attributes can be a JPA @Embeddable and
    // is stored as flattened columns on an owning entity; one carrying a list cannot
    // be embedded and keeps its JSON column.
    const embeds = attrs.every((a) => a.javaType === 'String');
    byKey.set(key, {
      javaType: vo.className,
      imports: [`${vo.package}.${vo.className}`],
      valueObject: vo,
      embeds,
      attrs,
      examples: def.examples,
    });
    valueObjects.push({
      kind: 'value-object',
      className: vo.className,
      package: vo.package,
      fields: attrs,
      attrs,
      embeds,
      examples: def.examples,
    });
  }
  return { byKey, valueObjects };
}

function typeOf(field, byKey) {
  if (field.convention) return CONVENTIONS[field.convention];
  const hit = byKey.get(naming.words(field.label).join(' '));
  return hit || { javaType: 'String', imports: [] };
}

// ---- top level ------------------------------------------------------------

export function parseModel({ modelDir, basePackage }) {
  const read = (f) => {
    const p = path.join(modelDir, f);
    if (!fs.existsSync(p)) throw new Error(`Missing model file: ${p}`);
    return fs.readFileSync(p, 'utf8');
  };

  const { byKey, valueObjects } = resolveTypes(
    parseDefinitions(read('business-definitions-raw.md')),
    basePackage,
  );

  const decorate = (fields) =>
    fields.map((f) => {
      const t = typeOf(f, byKey);
      return {
        ...f,
        javaType: t.javaType,
        imports: t.imports,
        conventionExpr: t.expr || null,
        ...(t.examples?.length ? { examples: t.examples } : {}),
        ...(t.valueObject ? { valueObject: t.valueObject, embeds: t.embeds, attrs: t.attrs } : {}),
      };
    });

  const events = parseSections(read('events.md')).map((s) => {
    if (!s.aggregate) throw new Error(`Event "${s.id}" has no <aggregate>:Id line`);
    if (s.headerLines.length > 1) {
      throw new Error(
        `Event "${s.id}" has more than one <aggregate>:Id line — an event always names ` +
          `exactly one aggregate; named key attributes (multiple "<path>:Key" lines) are a ` +
          `read-model-only concept.`,
      );
    }
    if (s.keyed) {
      throw new Error(
        `Event "${s.id}" uses <aggregate>:Key. ":Key" selects a persisting projection ` +
          `and is only meaningful on a read model — events always use ":Id".`,
      );
    }
    if (s.searchOnlyFields.length) {
      throw new Error(
        `Event "${s.id}" has a "??" (search-only criterion) field — search endpoints only ` +
          `exist on persisting read models, so "??" is meaningless on an event.`,
      );
    }
    return {
      id: s.id,
      name: s.props.name || s.id,
      aggregate: s.aggregate,
      fields: decorate(s.fields),
      ...naming.event(basePackage, s.id),
    };
  });
  const eventById = new Map(events.map((e) => [e.id, e]));

  const commands = parseSections(read('commands.md')).map((s) => {
    const producesId = s.props.produces;
    if (!producesId) throw new Error(`Command "${s.id}" has no "Produces:" line`);
    const produces = eventById.get(producesId);
    if (!produces) throw new Error(`Command "${s.id}" produces unknown event "${producesId}"`);
    if (s.searchOnlyFields.length) {
      throw new Error(
        `Command "${s.id}" has a "??" (search-only criterion) field — search endpoints only ` +
          `exist on persisting read models, so "??" is meaningless on a command.`,
      );
    }
    return {
      id: s.id,
      name: s.props.name || s.id,
      producesId,
      fields: decorate(s.fields),
      ...naming.command(basePackage, s.id),
    };
  });

  const readModels = parseSections(read('readmodels.md')).map((s) => {
    const subscribes = (s.props.subscribes || '').split(',').map((x) => x.trim()).filter(Boolean);
    if (subscribes.length === 0) throw new Error(`Read model "${s.id}" has no "Subscribes:" line`);
    for (const id of subscribes) {
      if (!eventById.has(id)) throw new Error(`Read model "${s.id}" subscribes unknown event "${id}"`);
    }
    if (s.headerLines.length === 0) {
      throw new Error(
        `Read model "${s.id}" has no <aggregate>:Id or <aggregate>:Key line. ` +
          `Use ":Id" for an on-demand projection (replayed per request) or ":Key" for a ` +
          `persisting one (JPA entity kept up to date on append, listable across aggregates).`,
      );
    }

    const decoratedFields = decorate(s.fields);
    const subscribedAggregates = new Set(subscribes.map((id) => eventById.get(id).aggregate));
    // Exactly one header line naming the subscribed aggregate is the classic form;
    // anything else — a second line, or a name that is not the aggregate — is a
    // named-key-attribute read model instead (see resolveKeyAttributePath above).
    const isClassic = s.headerLines.length === 1 && subscribedAggregates.has(s.headerLines[0].name);

    let aggregate, keyed, fields, headerKeyFields;
    if (isClassic) {
      aggregate = s.headerLines[0].name;
      keyed = s.headerLines[0].mode === 'Key';
      fields = injectIdentity(s, decoratedFields);
      headerKeyFields = [];
    } else {
      aggregate = null;
      keyed = true; // a composite natural key always needs a table to be looked up by
      fields = decoratedFields; // no implicit identity component in this mode
      headerKeyFields = s.headerLines.map(({ name, mode }) => {
        if (mode !== 'Key') {
          throw new Error(
            `Read model "${s.id}" names key attribute "${name}:${mode}" — a named key ` +
              `attribute (anything other than the single "<aggregate>:Id|Key" line naming ` +
              `the subscribed aggregate "${[...subscribedAggregates].join('/')}") must use ` +
              `":Key". ":Id" only selects the classic single-aggregate on-demand form.`,
          );
        }
        const resolved = resolveKeyAttributePath(name, decoratedFields);
        if (!resolved) {
          throw new Error(
            `Read model "${s.id}" names key attribute "${name}:Key" but no declared field's ` +
              `value-object attribute matches that path. It must decompose into an already-` +
              `declared field ("* <value-object field>") followed by exactly one of that ` +
              `value object's own attributes — e.g. "policyHolderName" needs a field ` +
              `"* policy holder" whose value object has an attribute "name". Add the missing ` +
              `field or fix the name; the generator does not guess.`,
          );
        }
        return {
          // The header line's name IS the camelCase field name already (unlike a
          // "* label" field, whose label still needs naming.field()'s space/hyphen
          // splitting) — running it through naming.field() here would flatten the
          // camelCase boundaries it already has (naming.field only splits on
          // whitespace/hyphen/underscore) into a single lowercased word.
          name: name[0].toLowerCase() + name.slice(1),
          label: name,
          key: true,
          javaType: resolved.attr.javaType,
          imports: [],
          derivedFrom: { field: resolved.field.name, attr: resolved.attr.name },
        };
      });
    }

    const keyFields = [...headerKeyFields, ...fields.filter((f) => f.key)];
    if (keyFields.length && !keyed) {
      throw new Error(
        `Read model "${s.id}" marks field(s) with ":Key" but is not a persisting ` +
          `("<aggregate>:Key") projection. ":Key" fields are only meaningful on a ` +
          `persisting read model, where they compose its composite id.`,
      );
    }
    if (s.searchOnlyFields.length && !keyed) {
      throw new Error(
        `Read model "${s.id}" has a "??" (search-only criterion) field but is an on-demand ` +
          `("<aggregate>:Id") projection — the search endpoint (and its Map<String,String> ` +
          `search param) only exists on a persisting ("<aggregate>:Key") read model.`,
      );
    }
    // Decorated the same way as regular fields (so a search-only criterion named
    // after a business concept gets the right javaType), but never merged into
    // `fields` — see parseSearchOnlyField.
    const searchOnlyFields = decorate(s.searchOnlyFields);

    // A "??" criterion has no stored value, so its decider (`matches<Field>`) can
    // only compute a match from data the read model's OWN fields actually carry —
    // there is no collaborator wiring, no hidden state, nothing else it can reach
    // for (the decider keeps a no-arg constructor forever). If not one field label
    // or value-object attribute even shares a word with the criterion, implementing
    // it silently would mean inventing data out of nothing — a decision for the
    // architect (add the underlying field, or confirm the criterion belongs
    // elsewhere), not something to guess your way through in a decider body. Fail
    // the model here, loudly, instead of letting an agent discover the gap only
    // after already writing a stub decider full of private state.
    requireSearchOnlyFieldsHaveData(s.id, fields, s.searchOnlyFields);

    return {
      id: s.id,
      name: s.props.name || s.id,
      aggregate,
      onDemand: !keyed,
      keyed,
      subscribes,
      fields,
      keyFields,
      searchOnlyFields,
      ...naming.readModel(basePackage, s.id, { keyed }),
    };
  });

  return { meta: { basePackage }, valueObjects, events, commands, readModels };
}

export { parseSections, parseField, parseSearchOnlyField, parseDefinitions, CONVENTIONS };
