// Model markdown -> normalised model.json. Pure parsing; no LLM, no filesystem
// discovery beyond reading the declared model files.
//
// Grammar (line-oriented):
//   ## <kebab-id>            starts an element
//   Name: <human name>
//   Produces: <event-id>     (commands)
//   Subscribes: <e1>, <e2>   (read models)
//   <aggregate>:Id           on-demand read model: hydrated from the stream per request
//   <aggregate>:Key          persisting read model: JPA entity keyed by the aggregate id,
//                            updated on append, listable across aggregates
//   * field name             plain payload attribute (passthrough)
//   * [field name]           system-generated/decided attribute
//   * [field name]:uuid|now  system-generated by convention (no decision needed)

import fs from 'node:fs';
import path from 'node:path';
import naming from './naming.js';

const CONVENTIONS = {
  uuid: { javaType: 'UUID', expr: 'UUID.randomUUID()', imports: ['java.util.UUID'] },
  now: { javaType: 'Instant', expr: 'Instant.now()', imports: ['java.time.Instant'] },
};

function parseSections(text) {
  const sections = [];
  let current = null;
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (line.startsWith('## ')) {
      current = { id: line.slice(3).trim(), props: {}, fields: [], aggregate: null, keyed: false };
      sections.push(current);
      continue;
    }
    if (!current || !line || line.startsWith('#')) continue;

    const field = line.match(/^\*\s+(.+)$/);
    if (field) {
      current.fields.push(parseField(field[1].trim()));
      continue;
    }
    // `foo:Id` -> on-demand, `foo:Key` -> persisting. Both name the same aggregate;
    // only the projection strategy differs, so both must be caught before the generic
    // `Prop: value` rule below (otherwise `policy:Key` silently becomes a property).
    const aggregate = line.match(/^([A-Za-z][\w -]*):(Id|Key)$/);
    if (aggregate) {
      current.aggregate = aggregate[1].trim();
      current.keyed = aggregate[2] === 'Key';
      continue;
    }
    const prop = line.match(/^([A-Za-z]+):\s*(.+)$/);
    if (prop) current.props[prop[1].toLowerCase()] = prop[2].trim();
  }
  return sections;
}

function parseField(raw) {
  // [policy number]:uuid  |  [policy number]  |  policy holder
  const m = raw.match(/^(\[)?([^\]]+?)(\])?(?::(\w+))?$/);
  if (!m) throw new Error(`Cannot parse field: "${raw}"`);
  const bracketed = Boolean(m[1] && m[3]);
  const label = m[2].trim();
  const convention = m[4] || null;
  if (convention && !CONVENTIONS[convention]) {
    throw new Error(`Unknown convention ":${convention}" on field "${label}". Known: ${Object.keys(CONVENTIONS).join(', ')}`);
  }
  if (convention && !bracketed) {
    throw new Error(`Convention ":${convention}" is only valid on a [bracketed] field ("${label}")`);
  }
  return { label, name: naming.field(label), bracketed, convention };
}

// ---- business definitions -------------------------------------------------

// Bullets under "# examples" are sample VALUES, never attributes. Only bullets
// outside that section describe the concept's structure.
function stripExamples(block) {
  const lines = block.split('\n');
  const kept = [];
  let inExamples = false;
  for (const line of lines) {
    const heading = line.match(/^#\s*(\w+)/);
    if (heading) inExamples = heading[1].toLowerCase() === 'examples';
    if (!inExamples) kept.push(line);
  }
  return kept.join('\n');
}

function parseDefinitions(text) {
  const defs = [];
  for (const block of text.split(/^-{3,}\s*$/m)) {
    const nameLine = block.match(/^#\s*name\s+(.+)$/m);
    if (!nameLine) continue;
    const attrs = [...stripExamples(block).matchAll(/^\*\s+(.+)$/gm)].map((m) => m[1].trim());
    defs.push({ name: nameLine[1].trim(), attributes: attrs });
  }
  return defs;
}

// A concept WITH listed attributes becomes a value object; without, a String.
function resolveTypes(defs, base) {
  const byKey = new Map();
  const valueObjects = [];
  for (const def of defs) {
    const key = naming.words(def.name).join(' ');
    if (def.attributes.length === 0) {
      byKey.set(key, { javaType: 'String', imports: [] });
      continue;
    }
    const vo = naming.valueObject(base, def.name);
    byKey.set(key, { javaType: vo.className, imports: [`${vo.package}.${vo.className}`] });
    valueObjects.push({
      kind: 'value-object',
      className: vo.className,
      package: vo.package,
      fields: def.attributes.map((a) => ({
        name: naming.field(a),
        // a "... list" attribute is a list of names; everything else is a plain String
        javaType: /\blist$/i.test(a.trim()) ? 'List<String>' : 'String',
      })),
    });
  }
  return { byKey, valueObjects };
}

function typeOf(field, byKey) {
  if (field.convention) return CONVENTIONS[field.convention];
  const hit = byKey.get(naming.words(field.label).join(' '));
  return hit || { javaType: 'String', imports: [] };
}

// ---- top level ------------------------------------------------------------

export function parseModel({ modelDir, basePackage }) {
  const read = (f) => {
    const p = path.join(modelDir, f);
    if (!fs.existsSync(p)) throw new Error(`Missing model file: ${p}`);
    return fs.readFileSync(p, 'utf8');
  };

  const { byKey, valueObjects } = resolveTypes(
    parseDefinitions(read('business-definitions-raw.md')),
    basePackage,
  );

  const decorate = (fields) =>
    fields.map((f) => {
      const t = typeOf(f, byKey);
      return { ...f, javaType: t.javaType, imports: t.imports, conventionExpr: t.expr || null };
    });

  const events = parseSections(read('events.md')).map((s) => {
    if (!s.aggregate) throw new Error(`Event "${s.id}" has no <aggregate>:Id line`);
    if (s.keyed) {
      throw new Error(
        `Event "${s.id}" uses <aggregate>:Key. ":Key" selects a persisting projection ` +
          `and is only meaningful on a read model — events always use ":Id".`,
      );
    }
    return {
      id: s.id,
      name: s.props.name || s.id,
      aggregate: s.aggregate,
      fields: decorate(s.fields),
      ...naming.event(basePackage, s.id),
    };
  });
  const eventById = new Map(events.map((e) => [e.id, e]));

  const commands = parseSections(read('commands.md')).map((s) => {
    const producesId = s.props.produces;
    if (!producesId) throw new Error(`Command "${s.id}" has no "Produces:" line`);
    const produces = eventById.get(producesId);
    if (!produces) throw new Error(`Command "${s.id}" produces unknown event "${producesId}"`);
    return {
      id: s.id,
      name: s.props.name || s.id,
      producesId,
      fields: decorate(s.fields),
      ...naming.command(basePackage, s.id),
    };
  });

  const readModels = parseSections(read('readmodels.md')).map((s) => {
    const subscribes = (s.props.subscribes || '').split(',').map((x) => x.trim()).filter(Boolean);
    if (subscribes.length === 0) throw new Error(`Read model "${s.id}" has no "Subscribes:" line`);
    for (const id of subscribes) {
      if (!eventById.has(id)) throw new Error(`Read model "${s.id}" subscribes unknown event "${id}"`);
    }
    if (!s.aggregate) {
      throw new Error(
        `Read model "${s.id}" has no <aggregate>:Id or <aggregate>:Key line. ` +
          `Use ":Id" for an on-demand projection (replayed per request) or ":Key" for a ` +
          `persisting one (JPA entity kept up to date on append, listable across aggregates).`,
      );
    }
    return {
      id: s.id,
      name: s.props.name || s.id,
      aggregate: s.aggregate,
      onDemand: !s.keyed,
      keyed: s.keyed,
      subscribes,
      fields: decorate(s.fields),
      ...naming.readModel(basePackage, s.id, { keyed: s.keyed }),
    };
  });

  return { meta: { basePackage }, valueObjects, events, commands, readModels };
}

export { parseSections, parseField, parseDefinitions, CONVENTIONS };
