import test from 'node:test';
import assert from 'node:assert/strict';
import { classifyFile, buildPatches, buildGwtPatch, CATEGORIES } from './patch.js';

// A minimal, well-formed generated file. The classifier parses Java structurally,
// so these have to be real enough to split into members.
const gen = (members) =>
  `// GENERATED by codegen -- DO NOT EDIT\npackage a.b;\n\npublic class C {\n${members}\n}\n`;

const file = (content, over = {}) => ({
  package: 'a.b',
  className: 'C',
  category: 'commands',
  content,
  ...over,
});

test('an absent file is CREATE and is the generator\'s job, not the agent\'s', () => {
  const entry = classifyFile({
    file: file(gen('  int x;')),
    currentContent: null,
    relPath: 'src/main/java/a/b/C.java',
  });
  assert.equal(entry.op, 'CREATE');
  assert.equal(entry.auto, true);
  // No hints: an auto entry is the generator's work and is never shown to an agent.
  assert.deepEqual(entry.hints, []);
});

test('an identical file is not work at all', () => {
  const content = gen('  int x;');
  assert.equal(classifyFile({ file: file(content), currentContent: content, relPath: 'p' }), null);
});

test('a PRESERVED-BY-HAND deviation is a decision already made — never reported as work', () => {
  const current = `// GENERATED by codegen -- DO NOT EDIT\n// PRESERVED-BY-HAND: tuned by hand\npackage a.b;\n\npublic class C {\n  int y;\n}\n`;
  assert.equal(classifyFile({ file: file(gen('  int x;')), currentContent: current, relPath: 'p' }), null);
});

test('a member the model has and the file lacks is ADD, and ADD is automatic', () => {
  const entry = classifyFile({
    file: file(gen('  int x;\n  int y;')),
    currentContent: gen('  int x;'),
    relPath: 'p',
  });
  assert.equal(entry.op, 'ADD');
  assert.equal(entry.auto, true);
  assert.ok(entry.members.length > 0);
});

test('ADD on a hand-owned logic file still needs an agent, and is deliberately restrained', () => {
  const entry = classifyFile({
    file: file(gen('  int x;\n  int y;'), { logic: true }),
    currentContent: gen('  int x;'),
    relPath: 'p',
  });
  assert.equal(entry.op, 'ADD');
  assert.equal(entry.auto, false);
  assert.match(entry.hints.join(' '), /only what a compile error or a failing test demands/);
});

test('a member whose body differs is UPDATE — never auto, never a wholesale rewrite', () => {
  const entry = classifyFile({
    file: file(gen('  void go() { a(); }')),
    currentContent: gen('  void go() { b(); }'),
    relPath: 'p',
  });
  assert.equal(entry.op, 'UPDATE');
  assert.equal(entry.auto, false);
  // The verb rule itself lives in the prompt renderer, stated once. The entry
  // carries only what is specific to it.
  assert.match(entry.hints.join(' '), /PRESERVED-BY-HAND/);
});

test('a `once` file at the current scaffold version is not work', () => {
  const current = '// SCAFFOLDED ONCE\n// scaffold-version: 2\npackage a.b;\n\npublic class C {\n  int mine;\n}\n';
  const entry = classifyFile({
    file: file(gen('  int x;'), { once: true, version: 2 }),
    currentContent: current,
    relPath: 'p',
  });
  assert.equal(entry, null);
});

test('a `once` file behind its template is UPDATE by hand-ported delta, not regeneration', () => {
  const current = '// SCAFFOLDED ONCE\n// scaffold-version: 1\npackage a.b;\n\npublic class C {\n  int mine;\n}\n';
  const entry = classifyFile({
    file: file(gen('  int x;'), { once: true, version: 2 }),
    currentContent: current,
    relPath: 'p',
  });
  assert.equal(entry.op, 'UPDATE');
  assert.equal(entry.auto, false);
  assert.match(entry.hints.join(' '), /v1 -> v2/);
  assert.match(entry.hints.join(' '), /accept-scaffold/);
});

test('buildPatches emits one document per category, with an honest agent count', () => {
  const entries = [
    { category: 'domain', op: 'CREATE', auto: true },
    { category: 'domain', op: 'UPDATE', auto: false },
    { category: 'events', op: 'ADD', auto: true },
  ];
  const patches = buildPatches(entries);
  assert.deepEqual(Object.keys(patches), CATEGORIES);
  assert.deepEqual(patches.domain.summary, { create: 1, add: 0, update: 1, needsAgent: 1 });
  assert.equal(patches.readmodels.entries.length, 0);
});

test('the GWT patch keeps the scenario name verbatim and names its spec file', () => {
  const queue = [
    {
      kind: 'gwt-scenario',
      detail: {
        scenario: 'when issue policy then policy number has next ordinal',
        file: 'gwt-policy-details.md',
        readModel: { package: 'a.b.policydetails' },
      },
      prompt: 'write the spec at `src/test/groovy/a/b/policydetails/PolicyDetailsSpec.groovy` ...',
    },
  ];
  const doc = buildGwtPatch(queue);
  const [e] = doc.entries;
  assert.equal(e.name, 'when issue policy then policy number has next ordinal');
  assert.equal(e.spec, 'src/test/groovy/a/b/policydetails/PolicyDetailsSpec.groovy');
  assert.equal(e.class, 'PolicyDetailsSpec');
  assert.equal(e.auto, false);
  assert.deepEqual(e.hints, []); // a derivable spec path needs no advice
});

test('a business rule is routed to the command decider, not to a read model', () => {
  const doc = buildGwtPatch([
    {
      kind: 'business-rule',
      detail: { rule: 'A policy must have a holder.', command: { package: 'a.b.issuepolicy' } },
      prompt: 'spec at `src/test/groovy/a/b/issuepolicy/IssuePolicySpec.groovy`',
    },
  ]);
  assert.equal(doc.entries[0].kind, 'business-rule');
  assert.equal(doc.entries[0].source, 'business-rules-raw.md');
  assert.equal(doc.entries[0].package, 'a.b.issuepolicy');
});

test('an underivable spec path is reported, never guessed', () => {
  const doc = buildGwtPatch([
    { kind: 'business-rule', detail: { rule: 'r', command: null }, prompt: 'could not map' },
  ]);
  assert.equal(doc.entries[0].spec, null);
  assert.match(doc.entries[0].hints.join(' '), /report it, do not guess/);
});
