// --- scanner -----------------------------------------------------------------

// GENERATE_TEST_DATA scanner: pending test-data work, cross-referenced from the
// command list against the on-disk TestDataAbility content.
//
// Where the data comes from:
//   1. business-definitions-raw.md `# examples` bullets, deterministically (see
//      ./emit.js — a scalar concept's first example becomes the constant's value).
//   2. the agent, for everything else: the scaffold emits `= null` and the
//      GENERATE_TEST_DATA step prompts until every constant holds data or is
//      deliberately opted out with a trailing `// no test data` marker.

import naming from '../../model/naming.js';
import { javaString } from './emit.js';

const constantLine = (src, name) => {
  const re = new RegExp(`^\\s*[\\w.$<>\\[\\],\\s]+\\s+${name}\\s*=`);
  return src.split('\n').find((l) => re.test(l)) ?? null;
};

const hasMember = (src, name) => new RegExp(`\\b${name}\\s*\\(`).test(src);

/**
 * Hint telling the agent where a field's data comes from. Pure.
 */
export function testDataHint(field) {
  const examples = field.examples || [];
  if (field.convention) return `system-generated by convention — leave null unless a scenario overrides it`;
  if (field.bracketed) return `[${field.label}] is a decision — standing default only if scenarios want one`;
  if (examples.length > 0) {
    if (field.valueObject) {
      const attrs = (field.attrs || []).map((a) => a.name).join(', ');
      return `business definition example: "${examples[0]}" — split it across attributes (${attrs}) or invent your own`;
    }
    return `business definition example: ${javaString(examples[0])}`;
  }
  return `no example in business-definitions-raw.md — invent one, or mark the line // no test data`;
}

/**
 * Pending test-data work, computed from the command list and the on-disk
 * TestDataAbility content. Pure: content null means the file does not exist yet
 * (the emitter's CREATE covers it; nothing to prompt for). Entries are deduped
 * across commands — two commands sharing a field label share one constant.
 */
export function missingTestData({ commands, content }) {
  if (!commands?.length || content == null) return [];
  const entries = [];
  const reported = new Set();
  const push = (entry) => {
    const key = entry.members.join('|');
    if (reported.has(key)) return;
    reported.add(key);
    entries.push(entry);
  };

  for (const c of commands) {
    const builderMethod = naming.defaultBuilderMethod(c.className);
    let dataPending = false;
    for (const f of c.fields) {
      const name = naming.testDataConstant(f.label);
      const line = constantLine(content, name);
      if (line == null) {
        dataPending = true;
        push({
          kind: 'test-data',
          name,
          op: 'ADD',
          auto: false,
          members: [name],
          hints: [`${f.javaType} ${name} — command "${c.id}" field "${f.label}" has no test-data constant`, testDataHint(f)],
        });
      } else if (/=\s*null\s*;/.test(line) && !line.includes('no test data')) {
        dataPending = true;
        push({
          kind: 'test-data',
          name,
          op: 'ADD',
          auto: false,
          members: [name],
          hints: [`${name} is still null — its value IS the default the ${c.abilityClassName} DSL pre-sets`, testDataHint(f)],
        });
      }
    }
    // Data before wiring: a default-builder body is nothing but references to the
    // constants, so it is filled out last. Prompting for both at once hands the
    // agent a method whose every line still names a `= null` constant.
    if (!dataPending && !hasMember(content, builderMethod)) {
      push({
        kind: 'test-data',
        name: builderMethod,
        op: 'ADD',
        auto: false,
        members: [`${builderMethod}()`],
        hints: [
          `command "${c.id}" has no default builder — the generated ${c.abilityClassName} DSL calls ` +
            `${builderMethod}(), so without it the build is red`,
        ],
      });
    }
  }
  return entries;
}
