// Model -> Angular files. Every path and every identifier is a pure function of
// the event model, so regenerating is idempotent and the inventory below is the
// complete list of frontend scaffolding. Nothing else may be hand-written.
//
// Two ownership modes:
//   once: false -> GENERATED, overwritten on every run
//   once: true  -> scaffolded when absent, never touched again (yours)

import naming from './naming.js';

const GEN = '// GENERATED by frontend-development/scripts/codegen — DO NOT EDIT.\n' +
  '// Change the event model (uis.md / commands.md / readmodels.md) and regenerate.\n';
const ONCE = '// SCAFFOLDED ONCE by frontend-development/scripts/codegen — this file is YOURS.\n';

function contracts(page, apiBase) {
  const out = [GEN];
  // Structured business definitions, mirroring the Java records the backend
  // generates from the same `business-definitions-raw.md`. A field typed by one of
  // these is an object on the wire — never a string.
  for (const obj of page.objectTypes || []) {
    const fields = obj.fields.map((f) => `  ${f.name}: ${f.tsType};`).join('\n');
    out.push(
      `/** The \`${obj.label}\` business definition. */\n` +
        `export interface ${obj.name} {\n${fields}\n}`,
    );
  }
  for (const cmd of page.commands) {
    // Mirrors the generated `<Cmd>` Java record component-for-component, so the
    // body is wire-compatible by construction. A [bracketed] field is decided
    // server-side, so it stays optional and a form must never collect it.
    const fields = cmd.fields.length
      ? cmd.fields
          .map((f) =>
            f.bracketed
              ? `  /** decided server-side — do not collect in a form */\n  ${f.name}?: ${f.tsType};`
              : `  ${f.name}: ${f.tsType};`,
          )
          .join('\n')
      : '  // this command carries no fields';
    out.push(
      `/** Body of \`POST ${apiBase}/${cmd.id}\` — the \`${cmd.id}\` command. */\n` +
        `export interface ${naming.payload(cmd.id)} {\n${fields}\n}\n\n` +
        `export const ${constName(cmd.id)}_ENDPOINT = '${apiBase}/${cmd.id}';`,
    );
  }
  for (const view of page.views) {
    const fields = view.fields.length
      ? view.fields.map((f) => `  ${f.name}: ${f.tsType};`).join('\n')
      : '  // no columns declared in readmodels.md';
    out.push(
      `/** Projection of the \`${view.id}\` read model. */\n` +
        `export interface ${naming.view(view.id)} {\n${fields}\n}\n\n` +
        (view.collection
          ? `export const ${constName(view.id)}_ENDPOINT = '${apiBase}/${view.id}';`
          : `export const ${naming.camel(view.id)}Endpoint = (aggregateId: string) =>\n` +
            `  \`${apiBase}/${view.id}/\${aggregateId}\`;`),
    );
  }
  if (out.length === 1) out.push('export {};');
  return out.join('\n\n') + '\n';
}

const constName = (id) => naming.words(id).join('_').toUpperCase();

// Empty value for a form field, matching its generated type exactly.
function initValue(f, indent) {
  if (f.object) {
    const inner = f.object.fields
      .map((sf) => `${indent}  ${sf.name}: ${initValue(sf, `${indent}  `)},`)
      .join('\n');
    return `{\n${inner}\n${indent}}`;
  }
  return f.tsType === 'string[]' ? "['']" : "''";
}

// Whatever a template uses must be declared in `imports`, and Angular warns
// (NG8113) about anything declared but unused. Since the template is owned, the
// import list has to be owned too — the generator only seeds it from the model.
function pageImports(page) {
  const seed = page.commands.length ? ['FormsModule'] : [];
  const lines = [
    ONCE,
    '// Angular imports for this page\'s template. Add RouterLink, pipes, child',
    '// components... here as the template needs them; drop what it stops using.',
    '',
  ];
  if (seed.includes('FormsModule')) lines.push(`import { FormsModule } from '@angular/forms';`);
  lines.push('');
  lines.push(`export const ${page.importsConst} = [${seed.join(', ')}];`);
  return lines.join('\n') + '\n';
}

function component(page) {
  const hasViews = page.views.length > 0;
  const angular = ['Component', 'inject', ...(hasViews ? ['OnInit'] : [])];

  const lines = [GEN, `import { ${angular.join(', ')} } from '@angular/core';`];
  if (page.aggregateParam) lines.push(`import { ActivatedRoute } from '@angular/router';`);
  if (page.commands.length) {
    lines.push(
      `import type {\n${page.commands.map((c) => `  ${naming.payload(c.id)},`).join('\n')}\n} from './${page.contractsFile.replace(/\.ts$/, '')}';`,
    );
  }
  lines.push(`import { ${page.importsConst} } from './${page.importsFile.replace(/\.ts$/, '')}';`);
  lines.push(`import { ${page.storeClassName} } from './${page.storeFile.replace(/\.ts$/, '')}';`);
  lines.push('');
  lines.push('@Component({');
  lines.push(`  selector: '${page.selector}',`);
  lines.push(`  imports: [${page.importsConst}],`);
  lines.push(`  templateUrl: './${page.templateFile}',`);
  lines.push(`  styleUrl: './${page.styleFile}',`);
  lines.push(`  providers: [${page.storeClassName}],`);
  lines.push('})');
  lines.push(`export class ${page.className}${hasViews ? ' implements OnInit' : ''} {`);
  lines.push(`  protected readonly store = inject(${page.storeClassName});`);
  if (page.aggregateParam) {
    lines.push(`  private readonly route = inject(ActivatedRoute);`);
    lines.push('');
    lines.push(
      `  /** Route is '${page.routePath}' because this page renders an :Id read model. */`,
    );
    lines.push(
      `  protected readonly aggregateId = this.route.snapshot.paramMap.get('aggregateId') ?? '';`,
    );
  }
  if (hasViews) {
    lines.push('');
    lines.push('  ngOnInit(): void {');
    for (const v of page.views) {
      const arg = v.collection ? '' : 'this.aggregateId';
      lines.push(`    void this.store.${naming.loadMethod(v.id)}(${arg});`);
    }
    lines.push('  }');
  }
  for (const c of page.commands) {
    // Form state is the command's own shape, so it is derived too. Bracketed
    // fields are optional server-side decisions and get no input binding.
    // A structured field is initialised as a nested object so the body matches the
    // Java record; a list starts with one empty entry so the form has one input.
    const init = c.fields
      .filter((f) => !f.bracketed)
      .map((f) => `    ${f.name}: ${initValue(f, '    ')},`)
      .join('\n');
    lines.push('');
    lines.push(`  protected readonly ${naming.camel(c.id)}Form: ${naming.payload(c.id)} = {`);
    if (init) lines.push(init);
    lines.push('  };');
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

// The HTTP client. Fully derived: the backend controllers are generated from the
// same event model, so method, path, body and response type are all decided by
// the model — there is nothing here for a human to choose.
//   command      -> POST <base>/<command-id>, body <Cmd>, returns the aggregate id
//   read model :Key -> GET <base>/<id>            -> View[]
//   read model :Id  -> GET <base>/<id>/{aggregateId} -> View
function api(page) {
  const types = [
    ...page.commands.map((c) => naming.payload(c.id)),
    ...page.views.map((v) => naming.view(v.id)),
  ];
  const endpoints = [
    ...page.commands.map((c) => `${constName(c.id)}_ENDPOINT`),
    ...page.views.map((v) =>
      v.collection ? `${constName(v.id)}_ENDPOINT` : `${naming.camel(v.id)}Endpoint`,
    ),
  ];
  const contractsPath = `./${page.contractsFile.replace(/\.ts$/, '')}`;

  const lines = [GEN, `import { Injectable, inject } from '@angular/core';`];
  if (types.length) {
    lines.push(`import { HttpClient } from '@angular/common/http';`);
    lines.push(`import { firstValueFrom } from 'rxjs';`);
    lines.push(`import type {\n${types.map((t) => `  ${t},`).join('\n')}\n} from '${contractsPath}';`);
    lines.push(`import {\n${endpoints.map((t) => `  ${t},`).join('\n')}\n} from '${contractsPath}';`);
  }
  lines.push('');
  lines.push(`@Injectable({ providedIn: 'root' })`);
  lines.push(`export class ${page.apiClassName} {`);
  if (types.length) lines.push('  private readonly http = inject(HttpClient);');

  for (const c of page.commands) {
    lines.push('');
    lines.push(`  /** \`POST\` the \`${c.id}\` command. Resolves to the new aggregate id. */`);
    lines.push(
      `  ${naming.postMethod(c.id)}(payload: ${naming.payload(c.id)}): Promise<string> {`,
    );
    lines.push(
      `    return firstValueFrom(this.http.post<string>(${constName(c.id)}_ENDPOINT, payload));`,
    );
    lines.push('  }');
  }
  for (const v of page.views) {
    const type = v.collection ? `${naming.view(v.id)}[]` : naming.view(v.id);
    const url = v.collection ? `${constName(v.id)}_ENDPOINT` : `${naming.camel(v.id)}Endpoint(aggregateId)`;
    lines.push('');
    lines.push(`  /** \`GET\` the \`${v.id}\` read model. */`);
    lines.push(`  ${naming.getMethod(v.id)}(${v.collection ? '' : 'aggregateId: string'}): Promise<${type}> {`);
    lines.push(`    return firstValueFrom(this.http.get<${type}>(${url}));`);
    lines.push('  }');
  }
  if (!types.length) {
    lines.push('  // standalone page: uis.md wires it to no command and no read model');
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

function store(page) {
  const types = [
    ...page.commands.map((c) => naming.payload(c.id)),
    ...page.views.map((v) => naming.view(v.id)),
  ];
  const contractsPath = `./${page.contractsFile.replace(/\.ts$/, '')}`;

  const lines = [
    ONCE,
    '// Page state, pre-wired to the generated API client. Everything below already',
    '// works; extend it only when a GWT scenario needs behavior the model cannot',
    '// express (navigate on success, client-side validation, derived views).',
    '',
    `import { Injectable, inject, signal } from '@angular/core';`,
    `import { ${page.apiClassName} } from './${page.apiFile.replace(/\.ts$/, '')}';`,
  ];
  if (types.length) {
    lines.push(`import type {\n${types.map((t) => `  ${t},`).join('\n')}\n} from '${contractsPath}';`);
  }
  lines.push('');
  lines.push('@Injectable()');
  lines.push(`export class ${page.storeClassName} {`);
  lines.push(`  private readonly api = inject(${page.apiClassName});`);
  lines.push('');
  lines.push('  readonly pending = signal(false);');
  lines.push('  readonly error = signal<string | null>(null);');
  for (const v of page.views) {
    const type = v.collection ? `${naming.view(v.id)}[]` : `${naming.view(v.id)} | null`;
    lines.push(`  readonly ${naming.viewSignal(v.id)} = signal<${type}>(${v.collection ? '[]' : 'null'});`);
  }
  for (const c of page.commands) {
    lines.push(`  readonly ${naming.camel(c.id)}Result = signal<string | null>(null);`);
  }

  for (const v of page.views) {
    const args = v.collection ? '' : 'aggregateId: string';
    lines.push('');
    lines.push(`  async ${naming.loadMethod(v.id)}(${args}): Promise<void> {`);
    lines.push(`    await this.run(async () => {`);
    lines.push(
      `      this.${naming.viewSignal(v.id)}.set(await this.api.${naming.getMethod(v.id)}(${v.collection ? '' : 'aggregateId'}));`,
    );
    lines.push('    });');
    lines.push('  }');
  }
  for (const c of page.commands) {
    lines.push('');
    lines.push(
      `  async ${naming.triggerMethod(c.id)}(payload: ${naming.payload(c.id)}): Promise<void> {`,
    );
    lines.push(`    await this.run(async () => {`);
    lines.push(
      `      this.${naming.camel(c.id)}Result.set(await this.api.${naming.postMethod(c.id)}(payload));`,
    );
    lines.push('    });');
    lines.push('  }');
  }

  lines.push('');
  lines.push('  private async run(action: () => Promise<void>): Promise<void> {');
  lines.push('    this.pending.set(true);');
  lines.push('    this.error.set(null);');
  lines.push('    try {');
  lines.push('      await action();');
  lines.push('    } catch (cause) {');
  lines.push('      this.error.set(cause instanceof Error ? cause.message : String(cause));');
  lines.push('    } finally {');
  lines.push('      this.pending.set(false);');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  return lines.join('\n') + '\n';
}

// One form control per field, shaped like the field's generated type. A structured
// field becomes a fieldset of nested controls and a list one input per entry, so
// `[(ngModel)]` always writes a value of the declared type. Binding a plain input
// to an object or a list is exactly what makes the backend fail to deserialise.
function formControl(field, expr, nameBase, indent) {
  if (field.object) {
    const out = [`${indent}<fieldset>`, `${indent}  <legend>${field.label}</legend>`];
    for (const sub of field.object.fields) {
      out.push(...formControl(sub, `${expr}.${sub.name}`, `${nameBase}_${sub.name}`, `${indent}  `));
    }
    out.push(`${indent}</fieldset>`);
    return out;
  }
  if (field.tsType === 'string[]') {
    return [
      `${indent}<fieldset>`,
      `${indent}  <legend>${field.label}</legend>`,
      `${indent}  @for (entry of ${expr}; track $index) {`,
      `${indent}    <input name="${nameBase}_{{ $index }}" [(ngModel)]="${expr}[$index]" />`,
      `${indent}  }`,
      `${indent}</fieldset>`,
    ];
  }
  return [
    `${indent}<label>`,
    `${indent}  ${field.label}`,
    `${indent}  <input name="${nameBase}" [(ngModel)]="${expr}" />`,
    `${indent}</label>`,
  ];
}

// Same shapes again, inline, for a table cell.
function cellValue(field, expr) {
  if (field.object) {
    return `<dl>${field.object.fields
      .map((sf) => `<dt>${sf.label}</dt><dd>${cellValue(sf, `${expr}.${sf.name}`)}</dd>`)
      .join('')}</dl>`;
  }
  if (field.tsType === 'string[]') {
    return `<ul>@for (entry of ${expr}; track $index) {<li>{{ entry }}</li>}</ul>`;
  }
  return `{{ ${expr} }}`;
}

// Read-only rendering of one field, mirroring the same shapes. An object rendered
// with `{{ }}` would print "[object Object]", so it gets a nested list instead.
function viewValue(field, expr, indent) {
  if (field.object) {
    const out = [`${indent}<dd>`, `${indent}  <dl>`];
    for (const sub of field.object.fields) {
      out.push(`${indent}    <dt>${sub.label}</dt>`);
      out.push(...viewValue(sub, `${expr}.${sub.name}`, `${indent}    `));
    }
    out.push(`${indent}  </dl>`, `${indent}</dd>`);
    return out;
  }
  if (field.tsType === 'string[]') {
    return [
      `${indent}<dd>`,
      `${indent}  <ul>@for (entry of ${expr}; track $index) {<li>{{ entry }}</li>}</ul>`,
      `${indent}</dd>`,
    ];
  }
  return [`${indent}<dd>{{ ${expr} }}</dd>`];
}

// A seed template that already renders what the page is wired to. It is yours to
// replace — the point is that a freshly generated page is demonstrably talking to
// the backend, not a blank box that needs work before it shows anything.
function template(page) {
  const lines = [
    `<!-- SCAFFOLDED ONCE by frontend-development/scripts/codegen — this file is YOURS. -->`,
    `<section class="${page.dir}">`,
    `  <h1>${page.name}</h1>`,
  ];
  if (page.actor) lines.push(`  <!-- Actor: ${page.actor} -->`);
  lines.push('');
  lines.push(`  @if (store.error(); as message) {`);
  lines.push(`    <p class="error">{{ message }}</p>`);
  lines.push(`  }`);

  for (const v of page.views) {
    const sig = `store.${naming.viewSignal(v.id)}()`;
    lines.push('');
    lines.push(`  <!-- read model: ${v.id} -->`);
    if (v.collection) {
      lines.push(`  <table>`);
      lines.push(`    <thead>`);
      lines.push(`      <tr>${v.fields.map((f) => `<th>${f.label}</th>`).join('')}</tr>`);
      lines.push(`    </thead>`);
      lines.push(`    <tbody>`);
      lines.push(`      @for (row of ${sig}; track $index) {`);
      lines.push(`        <tr>${v.fields.map((f) => `<td>${cellValue(f, `row.${f.name}`)}</td>`).join('')}</tr>`);
      lines.push(`      }`);
      lines.push(`    </tbody>`);
      lines.push(`  </table>`);
    } else {
      lines.push(`  @if (${sig}; as ${naming.camel(v.id)}) {`);
      lines.push(`    <dl>`);
      for (const f of v.fields) {
        lines.push(`      <dt>${f.label}</dt>`);
        lines.push(...viewValue(f, `${naming.camel(v.id)}.${f.name}`, '      '));
      }
      lines.push(`    </dl>`);
      lines.push(`  }`);
    }
  }

  for (const c of page.commands) {
    const model = `${naming.camel(c.id)}Form`;
    lines.push('');
    lines.push(`  <!-- command: ${c.id} -->`);
    lines.push(`  <form (ngSubmit)="store.${naming.triggerMethod(c.id)}(${model})">`);
    for (const f of c.fields.filter((x) => !x.bracketed)) {
      lines.push(...formControl(f, `${model}.${f.name}`, f.name, '    '));
    }
    lines.push(`    <button type="submit" [disabled]="store.pending()">${c.name}</button>`);
    lines.push(`  </form>`);
  }
  lines.push(`</section>`);
  return lines.join('\n') + '\n';
}

// Just enough CSS to make the scaffolded page readable: one column, labels above
// their inputs, fieldsets visibly grouping the fields of a structured value, and
// a table/definition list you can actually scan. Scoped to the page's own class,
// so it is yours to replace wholesale.
const style = (page) =>
  `/* SCAFFOLDED ONCE by frontend-development/scripts/codegen — this file is YOURS. */
.${page.dir} {
  max-width: 48rem;
  margin: 0 auto;
  padding: 1.5rem;
  font-family: system-ui, sans-serif;
  line-height: 1.5;
  color: #1b1b1b;
}

.${page.dir} h1 {
  margin: 0 0 1.5rem;
  font-size: 1.5rem;
}

.${page.dir} .error {
  margin: 0 0 1rem;
  padding: 0.75rem 1rem;
  border-left: 3px solid #b3261e;
  background: #fdeceb;
  color: #b3261e;
}

/* form: one field per row, label above its input */
.${page.dir} form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  align-items: flex-start;
  margin: 1.5rem 0;
}

.${page.dir} label {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  width: 100%;
  font-weight: 600;
}

.${page.dir} input {
  width: 100%;
  padding: 0.5rem;
  border: 1px solid #b8b8b8;
  border-radius: 4px;
  font: inherit;
  font-weight: 400;
}

.${page.dir} input:focus {
  outline: 2px solid #1b6ef3;
  outline-offset: 1px;
}

/* a structured value or a list — visibly one group */
.${page.dir} fieldset {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  width: 100%;
  margin: 0;
  padding: 1rem;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.${page.dir} legend {
  padding: 0 0.25rem;
  font-weight: 600;
}

.${page.dir} button {
  padding: 0.5rem 1.25rem;
  border: 0;
  border-radius: 4px;
  background: #1b6ef3;
  color: #fff;
  font: inherit;
  cursor: pointer;
}

.${page.dir} button:disabled {
  background: #b8b8b8;
  cursor: not-allowed;
}

/* read models */
.${page.dir} table {
  width: 100%;
  margin: 1.5rem 0;
  border-collapse: collapse;
}

.${page.dir} th,
.${page.dir} td {
  padding: 0.5rem;
  border-bottom: 1px solid #e4e4e4;
  text-align: left;
  vertical-align: top;
}

.${page.dir} th {
  background: #f5f5f5;
}

.${page.dir} dl {
  margin: 1.5rem 0;
}

.${page.dir} dt {
  font-weight: 600;
}

.${page.dir} dd {
  margin: 0 0 0.75rem;
}

.${page.dir} dd dl {
  margin: 0.25rem 0 0 1rem;
}

.${page.dir} ul {
  margin: 0;
  padding-left: 1.25rem;
}
`;

// A smoke test that the generated wiring really reaches the backend contract.
// It is yours: frontend-implement adds the GWT scenarios alongside it.
function spec(page) {
  const wired = page.views.length > 0 || page.commands.length > 0;
  const endpointImports = page.views.map((v) =>
    v.collection ? `${constName(v.id)}_ENDPOINT` : `${naming.camel(v.id)}Endpoint`,
  );

  const lines = [
    ONCE.trimEnd(),
    `import { TestBed } from '@angular/core/testing';`,
    `import { provideRouter } from '@angular/router';`,
  ];
  if (wired) {
    lines.push(`import { provideHttpClient } from '@angular/common/http';`);
    lines.push(
      `import {\n  HttpTestingController,\n  provideHttpClientTesting,\n} from '@angular/common/http/testing';`,
    );
  }
  lines.push(`import { ${page.className} } from './${page.componentFile.replace(/\.ts$/, '')}';`);
  if (endpointImports.length) {
    lines.push(
      `import {\n${endpointImports.map((e) => `  ${e},`).join('\n')}\n} from './${page.contractsFile.replace(/\.ts$/, '')}';`,
    );
  }
  lines.push('');
  lines.push(`describe('${page.className}', () => {`);
  if (wired) lines.push('  let http: HttpTestingController;');
  lines.push('');
  lines.push('  beforeEach(async () => {');
  lines.push('    await TestBed.configureTestingModule({');
  lines.push(`      imports: [${page.className}],`);
  lines.push('      providers: [');
  lines.push('        provideRouter([]),');
  if (wired) lines.push('        provideHttpClient(),\n        provideHttpClientTesting(),');
  lines.push('      ],');
  lines.push('    }).compileComponents();');
  if (wired) lines.push('    http = TestBed.inject(HttpTestingController);');
  lines.push('  });');
  if (wired) {
    lines.push('');
    lines.push('  afterEach(() => http.verify());');
  }
  lines.push('');
  lines.push(`  it('renders and requests exactly what the event model wires it to', async () => {`);
  lines.push(`    const fixture = TestBed.createComponent(${page.className});`);
  lines.push('    await fixture.whenStable();');
  for (const v of page.views) {
    const url = v.collection
      ? `${constName(v.id)}_ENDPOINT`
      : `${naming.camel(v.id)}Endpoint('')`;
    lines.push('');
    lines.push(`    // GET ${v.id} fires on init because uis.md wires this page to it`);
    lines.push(`    http.expectOne(${url}).flush(${v.collection ? '[]' : 'null'});`);
    lines.push('    await fixture.whenStable();');
  }
  lines.push('');
  lines.push(`    expect(fixture.nativeElement.querySelector('h1')?.textContent)`);
  lines.push(`      .toContain('${page.name}');`);
  lines.push('  });');
  lines.push('});');
  return lines.join('\n') + '\n';
}

function routes(pages) {
  if (!pages.length) return GEN + `import { Routes } from '@angular/router';\n\nexport const pageRoutes: Routes = [];\n`;
  const imports = pages
    .map((p) => `import { ${p.className} } from './${p.dir}/${p.componentFile.replace(/\.ts$/, '')}';`)
    .join('\n');
  const entries = pages
    .map((p) => `  { path: '${p.routePath}', component: ${p.className}, title: '${p.name}' },`)
    .join('\n');
  return (
    GEN +
    `import { Routes } from '@angular/router';\n${imports}\n\n` +
    `/** One route per \`Type: html\` entry in uis.md. Spread this into app.routes.ts. */\n` +
    `export const pageRoutes: Routes = [\n${entries}\n];\n`
  );
}

export function emit(model, { pagesRoot, apiBase }) {
  const files = [];
  const at = (page, file) => `${pagesRoot}/${page.dir}/${file}`;

  for (const page of model.pages) {
    files.push({ path: at(page, page.contractsFile), content: contracts(page, apiBase) });
    files.push({ path: at(page, page.apiFile), content: api(page) });
    files.push({ path: at(page, page.componentFile), content: component(page) });
    files.push({ path: at(page, page.importsFile), content: pageImports(page), once: true });
    files.push({ path: at(page, page.storeFile), content: store(page), once: true });
    files.push({ path: at(page, page.templateFile), content: template(page), once: true });
    files.push({ path: at(page, page.styleFile), content: style(page), once: true });
    files.push({ path: at(page, page.specFile), content: spec(page), once: true });
  }
  files.push({ path: `${pagesRoot}/pages.routes.ts`, content: routes(model.pages) });
  return files;
}

export { contracts, api, component, pageImports, store, template, spec, routes };
